import Link from "next/link";
import {
  approveResetAdjustmentAction,
  closeResetDayAction,
  declineResetAdjustmentAction,
  openFirstWeeklyReviewAction,
  rebuildResetTodayAction,
  resolveNextWeekAction,
  saveDayOneRealismAction,
  savePatternFeedbackAction,
  saveWeeklyReflectionAction,
  rescheduleResetTaskAction,
  moveResetTaskToBacklogAction,
  pauseResetTodayAction,
  startResetAction,
} from "@/lib/actions/reset";
import type { ResetView } from "@/lib/reset/service";
import type { PlannedResetAction } from "@/lib/reset/engine";
import { DayCloseButton } from "@/components/celebrations/day-close-button";

export function ResetExperience({ view }: { view: ResetView }) {
  if (!view.available) return <EmptyStart canStart={view.canStartManually}/>;
  if (view.preparationEvening || view.day === 0) return <Preparation view={view}/>;
  const snapshot = view.snapshot;
  return <main className="py-mobile-shell md:py-shell-narrow pb-[calc(96px+env(safe-area-inset-bottom))]">
    <header className="py-animate-in mb-5 pt-2">
      <div className="flex items-center justify-between gap-3"><Link href="/today" className="min-h-11 py-3 text-[12px] font-semibold text-text-2">← Today</Link><span className="py-glass-pill text-[10px] text-text-2">Day {view.day} of 7</span></div>
      <div className="mt-2 py-progress-track"><div className="py-progress-fill transition-all duration-200" style={{width:`${Math.round(view.day/7*100)}%`}}/></div>
      <div className="py-eyebrow mt-5 text-accent-text">7-Day Project You+ Reset</div>
      <h1 className="m-0 mt-2 text-[30px] font-bold tracking-[-.045em] text-text-1">{view.definition?.headline}</h1>
      <p className="m-0 mt-2 max-w-[520px] text-[13px] leading-relaxed text-text-2">{view.definition?.focus}</p>
    </header>

    {view.day===1 && <section className="py-glass-soft py-animate-in mb-4 p-4"><div className="py-eyebrow text-accent-text">Your 7-Day Project You+ Reset starts now.</div><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">Your first week is designed to turn your plan into a system you can actually follow.</p></section>}

    {view.recovery.active && <section className="py-glass-soft py-animate-in mb-4 border-accent/15 p-4"><div className="py-eyebrow text-accent-text">Momentum restored by returning</div><h2 className="m-0 mt-1.5 text-[18px] font-semibold text-text-1">One difficult day did not change the goal.</h2><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">{view.recovery.message}</p>{view.recovery.actions.length>0&&<div className="mt-3 grid gap-2">{view.recovery.actions.map(action=><MiniAction key={action.key} action={action} label={action.recoveryTitle}/>)}</div>}</section>}

    <section className="py-glass-hero py-animate-in p-5 sm:p-6">
      <div className="py-eyebrow text-accent-text">Morning</div>
      <h2 className="m-0 mt-2 text-[22px] font-semibold tracking-[-.03em] text-text-1">{String(snapshot?.morning_summary?.headline ?? "Your day is ready.")}</h2>
      <p className="m-0 mt-2 text-[13px] leading-relaxed text-[#D4CEDD]">{String(snapshot?.morning_summary?.coach_message ?? view.definition?.focus ?? "")}</p>
      <div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Planned focus" value={`${view.priorities.length} action${view.priorities.length===1?"":"s"}`}/><Metric label="Approx. time" value={snapshot?.estimated_minutes ? `${snapshot.estimated_minutes} min` : "Flexible"}/></div>
      {Array.isArray(snapshot?.morning_summary?.schedule_constraints)&&snapshot.morning_summary.schedule_constraints.length>0&&<div className="mt-4 border-t border-white/[.06] pt-3"><div className="py-eyebrow">Important schedule constraints</div><div className="mt-2 grid gap-1.5">{snapshot.morning_summary.schedule_constraints.map((item:any)=><div key={item.id} className="text-[11px] text-text-3">{item.title} · {new Date(item.startAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</div>)}</div></div>}
    </section>

    <section className="py-animate-in mt-6"><div className="mb-3 flex items-end justify-between gap-3"><div><div className="py-eyebrow">Today</div><h2 className="m-0 mt-1 text-[21px] font-semibold tracking-[-.03em] text-text-1">Your real priorities</h2></div><Link href="/today" className="text-[11px] font-semibold text-accent-text">Open Today</Link></div>
      {view.priorities.length?<div className="grid gap-2.5">{view.priorities.map((action,index)=><ActionRow key={action.key} action={action} index={index}/>)}</div>:<div className="py-glass-soft p-4 text-[12px] leading-relaxed text-text-2">No validated action is due right now. Project You+ will not invent one to fill this screen.</div>}
    </section>

    <section className="py-glass-soft py-animate-in mt-5 p-4"><div className="flex items-start justify-between gap-3"><div><div className="py-eyebrow">Minimum successful day</div><h2 className="m-0 mt-1 text-[17px] font-semibold text-text-1">A smaller day still counts as evidence.</h2></div><span className="py-glass-pill text-[10px] text-text-2">Recovery-safe</span></div><div className="mt-3 grid gap-2">{view.minimumDay.length?view.minimumDay.map(action=><MiniAction key={action.key} action={action} label={action.minimumVersion??action.title}/>):<div className="text-[12px] text-text-3">No minimum actions are needed because no validated action is due.</div>}</div></section>

    {view.day >= 3 && view.consistencyTarget && <section className="py-glass-soft py-animate-in mt-5 p-4"><div className="py-eyebrow">Weekly consistency</div><p className="m-0 mt-2 text-[13px] font-semibold leading-relaxed text-text-1">{view.consistencyTarget.label}</p><p className="m-0 mt-1 text-[11.5px] leading-relaxed text-text-3">Consistency follows the plan’s real cadence. Consecutive-day streaks are not the target.</p></section>}

    {view.day >= 4 && <PatternSection view={view}/>} 
    {view.day >= 5 && <AdjustmentSection view={view}/>} 
    {view.day >= 6 && <TrajectorySection view={view}/>} 
    {view.day >= 7 && <WeeklyReviewSection view={view}/>} 

    {view.day < 7 && <CloseDaySection view={view}/>} 
    {view.day === 1 && view.closure && <DayOneCalibration/>}

    <section className="mt-5 flex items-center justify-between gap-3"><form action={rebuildResetTodayAction}><button type="submit" className="min-h-11 rounded-[14px] border border-white/[.08] px-4 text-[11.5px] font-semibold text-text-2">Rebuild today</button></form><span className="max-w-[250px] text-right text-[10.5px] leading-relaxed text-text-3">Only rebuild after your real plan or schedule changes.</span></section>
  </main>;
}

function EmptyStart({canStart}:{canStart:boolean}) { return <main className="py-mobile-shell md:py-shell-narrow"><section className="py-glass-hero mt-6 p-6"><div className="py-eyebrow text-accent-text">7-Day Project You+ Reset</div><h1 className="m-0 mt-2 text-[30px] font-bold tracking-[-.04em] text-text-1">Your first week should use the system you already built.</h1><p className="m-0 mt-2 text-[13px] leading-relaxed text-text-2">The Reset uses your current goals, actions, habits, schedule, score, and Weekly Review. It does not create a second challenge system.</p>{canStart?<form action={startResetAction} className="mt-5"><button className="py-liquid-button min-h-12 w-full" type="submit">Start my 7-Day Reset</button></form>:<Link href="/today" className="py-liquid-button mt-5 w-full">Go to Today</Link>}</section></main>; }
function Preparation({view}:{view:ResetView}) { return <main className="py-mobile-shell md:py-shell-narrow"><section className="py-glass-hero mt-6 p-6"><div className="py-eyebrow text-accent-text">Preparation evening</div><h1 className="m-0 mt-2 text-[30px] font-bold tracking-[-.04em] text-text-1">Your 7-Day Project You+ Reset starts tomorrow.</h1><p className="m-0 mt-3 text-[13px] leading-relaxed text-text-2">There isn’t enough realistic time left today for a useful Day 1, so Project You+ is not handing you an impossible plan.</p><div className="py-glass-soft mt-5 p-4"><div className="text-[12px] font-semibold text-text-1">Tomorrow: Build direction</div><div className="mt-1 text-[11.5px] leading-relaxed text-text-3">Start with the highest-value actions from the personal system you already approved.</div>{view.priorities.length>0&&<div className="mt-3 grid gap-2">{view.priorities.map((action,index)=><ActionRow key={action.key} action={action} index={index}/>)}</div>}<div className="mt-3 text-[10.5px] text-text-3">Approx. {view.snapshot?.estimated_minutes??0} min · you can use the minimum-day version if tomorrow changes.</div></div><Link href="/today" className="py-liquid-button mt-5 w-full">Return to Today</Link></section></main>; }

function CloseDaySection({view}:{view:ResetView}) {
  const actions = (view.snapshot?.planned_actions ?? []) as PlannedResetAction[];
  if (view.closure) return <section className="py-glass-soft py-animate-in mt-6 p-4"><div className="py-eyebrow">Evening close</div><h2 className="m-0 mt-1.5 text-[20px] font-semibold text-text-1">{view.closure.completion_percentage==null?"Today had no measurable actions due.":`You closed ${Math.round(Number(view.closure.completion_percentage))}% of today.`}</h2><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">{view.closure.coach_summary}</p>{view.closure.evening_summary?.importantWin&&<Info label="Important win" value={String(view.closure.evening_summary.importantWin)}/>}<div className="mt-3"><Info label="Recovery" value={String(view.closure.evening_summary?.recoverySuggestion??"Tomorrow’s plan stays available without punishment.")}/></div>{Array.isArray(view.closure.tomorrow_preview?.actions)&&<div className="mt-3 border-t border-white/[.06] pt-3"><div className="py-eyebrow">Tomorrow preview</div>{view.closure.tomorrow_preview.actions.length?<div className="mt-2 grid gap-1">{view.closure.tomorrow_preview.actions.map((item:any)=><div key={item.key} className="text-[11px] text-text-3">{item.title}</div>)}</div>:<div className="mt-1 text-[11px] text-text-3">No validated priority is scheduled yet.</div>}</div>}</section>;
  return <form action={closeResetDayAction} className="py-glass-soft py-animate-in mt-6 p-4"><div className="py-eyebrow">Evening</div><h2 className="m-0 mt-1.5 text-[20px] font-semibold text-text-1">Let’s close today.</h2><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">Closing the day records what happened. It never marks unfinished work complete.</p>
    <div className="mt-4 grid gap-3">{actions.filter(action=>action.due&&!action.optional).map(action=><div key={action.key} className="rounded-[14px] border border-white/[.06] bg-white/[.025] p-3"><div className="flex items-start gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${action.completed?"bg-emerald-400":"bg-white/20"}`}/><div className="min-w-0 flex-1"><div className="text-[12.5px] font-medium text-text-1">{action.title}</div>{action.completed?<div className="mt-1 text-[10.5px] text-emerald-300">Completed in your real system</div>:action.rescheduled?<div className="mt-1 text-[10.5px] text-accent-text">Moved to tomorrow</div>:<select name={`status:${action.key}`} defaultValue="skipped" className="mt-2 min-h-11 w-full rounded-xl border border-white/[.08] bg-[#111016] px-3 text-[12px] text-text-1"><option value="skipped">Skipped</option><option value="partial">Partially completed</option>{action.minimumVersion&&<option value="minimum">Used minimum version</option>}<option value="blocked">Blocked</option></select>}{!action.completed && !action.rescheduled && ["task","finance"].includes(action.sourceType) && action.sourceId && <><button formAction={rescheduleResetTaskAction} name="taskId" value={action.sourceId} type="submit" className="mt-2 min-h-10 text-[10.5px] font-semibold text-accent-text">Move to tomorrow</button><button formAction={moveResetTaskToBacklogAction} name="taskId" value={action.sourceId} type="submit" className="ml-3 mt-2 min-h-10 text-[10.5px] font-semibold text-text-3">Move to backlog</button></>} {!action.completed && <Link href="/coach" className="ml-3 inline-flex min-h-10 items-center text-[10.5px] font-semibold text-text-3">Ask Coach</Link>}</div></div>{action.completed&&<input type="hidden" name={`status:${action.key}`} value="completed"/>}{action.rescheduled&&<input type="hidden" name={`status:${action.key}`} value="rescheduled"/>}</div>)}</div>
    <label className="mt-4 block text-[11px] font-semibold text-text-2" htmlFor="reset-blocker">Main blocker <span className="font-normal text-text-3">(optional)</span></label><select id="reset-blocker" name="blocker" defaultValue="" className="mt-2 min-h-11 w-full rounded-xl border border-white/[.08] bg-[#111016] px-3 text-[12px] text-text-1"><option value="">No blocker to add</option><option value="ran_out_of_time">Ran out of time</option><option value="schedule_changed">Schedule changed</option><option value="low_energy">Low energy</option><option value="family_responsibility">Family responsibility</option><option value="forgot">Forgot</option><option value="plan_unrealistic">Plan was unrealistic</option><option value="no_longer_relevant">No longer relevant</option><option value="other">Something else</option></select>
    <label className="mt-4 block text-[11px] font-semibold text-text-2" htmlFor="reset-reflection">One note <span className="font-normal text-text-3">(optional)</span></label><textarea id="reset-reflection" name="reflection" maxLength={500} rows={2} className="mt-2 w-full rounded-xl border border-white/[.08] bg-[#111016] p-3 text-[12px] text-text-1 outline-none focus:border-accent/60" placeholder="What changed today?"/>
    <div className="mt-3 text-[10.5px] leading-relaxed text-text-3">Calculation: completed actions count 1; partial or minimum versions count 0.5; skipped, blocked, and rescheduled actions count 0. Only real actions due today are included.</div>
    <div className="mt-4 grid grid-cols-2 gap-2"><DayCloseButton/><button formAction={pauseResetTodayAction} className="min-h-12 w-full rounded-[14px] border border-white/[.08] px-3 text-[11px] font-semibold text-text-2" type="submit">Pause today without punishment</button></div>
  </form>;
}

function DayOneCalibration(){return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Workload calibration</div><h2 className="m-0 mt-1 text-[17px] font-semibold text-text-1">Did today feel realistic?</h2><div className="mt-3 grid grid-cols-2 gap-2">{[["yes","Yes"],["mostly","Mostly"],["too_much","Too much"],["too_little","Too little"]].map(([value,label])=><form action={saveDayOneRealismAction} key={value}><input type="hidden" name="feeling" value={value}/><button type="submit" className="min-h-11 w-full rounded-[13px] border border-white/[.08] bg-white/[.025] px-3 text-[11.5px] font-semibold text-text-2 transition duration-200 hover:border-accent/30">{label}</button></form>)}</div><p className="m-0 mt-2 text-[10.5px] leading-relaxed text-text-3">This is early evidence. Project You+ will not silently change your plan from one answer.</p></section>}

function PatternSection({view}:{view:ResetView}){if(view.patternInsufficient||!view.pattern)return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Learning</div><h2 className="m-0 mt-1 text-[18px] font-semibold text-text-1">Still learning your patterns.</h2><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">We need a little more real activity before making a useful conclusion.</p></section>;const pattern=view.pattern;return <section className="py-glass-soft mt-5 p-4"><div className="flex items-center justify-between gap-3"><div className="py-eyebrow">Early signal</div><span className="py-glass-pill text-[10px] text-text-2">{Math.round(Number(pattern.confidence)*100)}% confidence</span></div><h2 className="m-0 mt-2 text-[18px] font-semibold text-text-1">{pattern.summary}</h2><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">{pattern.why_it_matters}</p><div className="mt-3 text-[10.5px] text-text-3">Based on {pattern.observation_count} closed-day observations. This is a correlation, not a causal claim.</div>{!pattern.user_feedback&&<><div className="mt-4 text-[11px] font-semibold text-text-2">Does this feel accurate?</div><div className="mt-2 grid grid-cols-2 gap-2">{[["yes","Yes"],["partly","Partly"],["no","No"],["need_more_time","Need more time"]].map(([value,label])=><form action={savePatternFeedbackAction} key={value}><input type="hidden" name="feedback" value={value}/><button type="submit" className="min-h-11 w-full rounded-[13px] border border-white/[.08] bg-white/[.025] px-3 text-[11px] font-semibold text-text-2">{label}</button></form>)}</div></>}</section>}

function AdjustmentSection({view}:{view:ResetView}){const rec=view.adjustment;if(!rec)return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Coach adjustment</div><h2 className="m-0 mt-1 text-[18px] font-semibold text-text-1">Your starting system is working without a forced change.</h2><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">No adjustment is needed yet. Project You+ will not change something just to create a Day 5 moment.</p></section>;return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Coach adjustment</div><h2 className="m-0 mt-1.5 text-[18px] font-semibold text-text-1">{rec.suggestedAction}</h2><div className="mt-3 grid gap-2"><Info label="Observed" value={rec.observation}/><Info label="Why it may help" value={rec.reasonItMatters}/><Info label="Expected impact" value={rec.expectedImpact}/><Info label="What stays the same" value="Your goal and completed work stay intact."/></div>{rec.state==="pending"||rec.state==="accepted"?<><div className="mt-4 grid grid-cols-2 gap-2"><form action={approveResetAdjustmentAction}><input type="hidden" name="recommendationId" value={rec.id}/><button className="py-liquid-button min-h-11 w-full" type="submit">Approve adjustment</button></form><form action={declineResetAdjustmentAction}><input type="hidden" name="recommendationId" value={rec.id}/><button className="min-h-11 w-full rounded-[14px] border border-white/[.08] px-3 text-[11px] font-semibold text-text-2" type="submit">Keep current plan</button></form></div><Link href="/coach" className="mt-2 inline-flex min-h-11 items-center text-[11px] font-semibold text-text-3">Edit with Coach</Link></>:<div className="mt-3 text-[11px] font-semibold text-accent-text">{rec.state==="completed"?"Approved and applied":"Not applied"}</div>}</section>}

function TrajectorySection({view}:{view:ResetView}){const t=view.trajectory;if(!t)return null;return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Trajectory</div><h2 className="m-0 mt-1.5 text-[20px] font-semibold text-text-1">Your trajectory is becoming clearer.</h2><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Starting score" value={t.starting==null?"Still calibrating":`${t.starting} · provisional`}/><Metric label="Current score" value={t.current==null?"Still calibrating":`${t.current} · ${t.confidence} confidence`}/></div><p className="m-0 mt-3 text-[12px] leading-relaxed text-text-2">{t.direction==="up"?`Your score is up ${t.movement} point${t.movement===1?"":"s"} on the same scoring version.`:t.direction==="flat"?"Your score is still calibrating, but the evidence from completed and closed days is becoming more useful.":t.direction==="down"?`Your score moved ${Math.abs(Number(t.movement))} point lower. One difficult day does not erase the week, and the scoring engine limits abrupt drops.`:"There is not enough comparable score evidence yet, so Project You+ is not inventing a number."}</p><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Actions completed" value={String(t.actionsCompleted)}/><Metric label="Habit consistency" value={t.habitCompletionPct==null?"Not scheduled":`${t.habitCompletionPct}%`}/><Metric label="Training" value={`${t.workoutsCompleted}/${t.workoutsPlanned}`}/><Metric label="Financial actions" value={String(t.financeActionsCompleted)}/><Metric label="Recoveries" value={String(t.recoveryCount)}/><Metric label="Score coverage" value={t.coverage==null?"Calibrating":`${t.coverage}%`}/></div><div className="mt-4 grid gap-2"><Info label="Positive signal" value={t.positiveSignal}/><Info label="Still calibrating" value={t.calibratingArea}/></div><div className="mt-3 text-[10.5px] text-text-3">Stage: {t.stage??"Foundation"} · 1% remains evidence-gated and unavailable from one first week.</div></section>}

function WeeklyReviewSection({view}:{view:ResetView}) {
  const review=view.weeklyReview;
  if(!review)return <section className="py-glass-soft mt-5 p-4"><div className="py-eyebrow">Weekly Review</div><p className="m-0 mt-2 text-[12px] text-text-2">Your first-week review is being built from real activity. Your Reset remains ready to review rather than failing.</p></section>;
  if(!view.enrollment?.review_opened_at)return <section className="py-glass-hero mt-6 p-5"><div className="py-eyebrow text-accent-text">Your First Week</div><h2 className="m-0 mt-2 text-[24px] font-semibold tracking-[-.03em] text-text-1">Your first week is ready to review.</h2><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">Built from your actual closed days, planned actions, habits, training, financial actions, patterns, and canonical score evidence.</p><form action={openFirstWeeklyReviewAction} className="mt-4"><button className="py-liquid-button min-h-11 w-full" type="submit">Open my Weekly Review</button></form></section>;
  const d=review.details??{},trajectory=d.trajectory??{},tasks=d.taskCompletion??{},habits=d.habitConsistency??{},training=d.training??{},finance=d.finance??{},patterns=d.patterns??{},daily=Array.isArray(d.dailySummaries)?d.dailySummaries:[];
  const habitLines:string[]=(habits.byHabit??[]).map((item:any)=>`${item.title}: ${item.completed}/${item.planned} full · ${item.minimum} minimum · ${item.completionPercentage??0}%`);
  const bodyLines:string[]=(training.bodyCompositionEntries??[]).map((item:any)=>`${String(item.metricType).replaceAll("_"," ")}: ${item.value} · ${new Date(item.recordedAt).toLocaleDateString()}`);
  const financeLines=[`${finance.actionsCompleted??0} of ${finance.actionsPlanned??0} financial actions completed`,finance.goal?`Primary money goal: ${finance.goal.title} · ${finance.goal.progress??0}% progress`:"No active financial goal was included in this Reset",finance.amountMovement==null?"No dollar movement is shown because no verified contribution amount was recorded.":`Recorded movement: ${finance.amountMovement}`];
  const patternLines=patterns.confirmed?.length?patterns.confirmed:patterns.earlySignals?.length?patterns.earlySignals:patterns.rejected?.length?patterns.rejected.map((item:string)=>`Rejected: ${item}`):["More evidence is needed before confirming a pattern."];
  return <section className="py-glass-hero mt-6 p-5"><div className="py-eyebrow text-accent-text">Your First Week</div><h2 className="m-0 mt-2 text-[24px] font-semibold tracking-[-.03em] text-text-1">Your first week is ready to review.</h2>
    <div className="mt-5 grid gap-3"><ReviewBlock title="Trajectory" lines={[`Starting: ${trajectory.startingScore??"Still calibrating"}`,`Current: ${trajectory.currentScore??"Still calibrating"}`,`Net movement: ${trajectory.netMovement==null?"Not comparable yet":trajectory.netMovement>0?`+${trajectory.netMovement}`:String(trajectory.netMovement)}`,`State: ${trajectory.stage??"Foundation"} · ${trajectory.confidence??"low"} confidence`]}/><ReviewBlock title="Task completion" lines={[`${tasks.completed??0} of ${tasks.planned??0} planned task appearances completed`,`${tasks.partial??0} partial · ${tasks.rescheduled??0} rescheduled · ${tasks.blocked??0} blocked`,tasks.completionPercentage==null?"No valid aggregate percentage yet":`${tasks.completionPercentage}% weighted closure`]}/><ReviewBlock title="Habit consistency" lines={habitLines.length?habitLines:[`${habits.completed??0} of ${habits.planned??0} planned habit appearances completed`,`${habits.minimumVersionsUsed??0} minimum versions used`,`${habits.recoveryCount??0} recoveries recorded`]}/><ReviewBlock title="Training" lines={[`${training.completed??0} of ${training.planned??0} scheduled sessions completed`,`${training.totalTrainingMinutes??0} recorded planned minutes from completed Reset sessions`,...(bodyLines.length?bodyLines:["No weight or body-composition entry was recorded during this window."])]}/><ReviewBlock title="Financial movement" lines={financeLines}/><ReviewBlock title="Patterns learned" lines={patternLines}/></div>
    <div className="mt-5"><div className="py-eyebrow">Daily summaries</div><div className="mt-2 grid gap-2">{daily.map((item:any)=><div key={item.date} className="rounded-[14px] border border-white/[.06] bg-white/[.025] p-3"><div className="flex items-center justify-between gap-3"><div className="text-[11.5px] font-semibold text-text-1">Day {item.day}</div><div className="text-[10.5px] text-text-3">{item.closed?(item.completionPercentage==null?"Closed · no due actions":`${item.completionPercentage}% closed`):"Not closed"}</div></div><div className="mt-2 grid gap-1 text-[10.5px] leading-relaxed text-text-3">{item.mainWin&&<div>Win: {item.mainWin}</div>}{item.mainBlocker&&<div>Blocker: {String(item.mainBlocker).replaceAll("_"," ")}</div>}{item.recoveryAction&&<div>Recovery: {item.recoveryAction}</div>}</div></div>)}</div></div>
    <div className="mt-4 rounded-[14px] border border-white/[.06] bg-white/[.025] p-3"><div className="py-eyebrow">Coach summary</div><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">{d.coachSummary??review.summary}</p></div>
    <form action={saveWeeklyReflectionAction} className="mt-5 rounded-[14px] border border-white/[.06] bg-white/[.02] p-3"><div className="py-eyebrow">Your reflection</div><label className="mt-3 block text-[10.5px] font-semibold text-text-2">What are you most proud of?</label><select name="proudOf" className="mt-1 min-h-11 w-full rounded-xl border border-white/[.08] bg-[#111016] px-3 text-[11px] text-text-1"><option>Completed important actions</option><option>Returned after a difficult day</option><option>Kept a routine</option><option>Learned what works</option><option>Something else</option></select><label className="mt-3 block text-[10.5px] font-semibold text-text-2">What felt harder than expected?</label><select name="harderThanExpected" className="mt-1 min-h-11 w-full rounded-xl border border-white/[.08] bg-[#111016] px-3 text-[11px] text-text-1"><option>Time</option><option>Energy</option><option>Schedule changes</option><option>Plan size</option><option>Nothing specific</option></select><label className="mt-3 block text-[10.5px] font-semibold text-text-2">What should Project You+ adjust?</label><select name="adjustNext" className="mt-1 min-h-11 w-full rounded-xl border border-white/[.08] bg-[#111016] px-3 text-[11px] text-text-1"><option>Keep the system steady</option><option>Reduce workload</option><option>Change timing</option><option>Add more structure</option></select><textarea name="note" maxLength={500} rows={2} className="mt-2 w-full rounded-xl border border-white/[.08] bg-[#111016] p-3 text-[11px] text-text-1" placeholder="Optional note"/><button type="submit" className="mt-2 min-h-11 text-[11px] font-semibold text-accent-text">Save reflection</button></form>
    {!view.enrollment?.next_week_resolution&&<div className="mt-5"><div className="py-eyebrow">Next week</div><h3 className="m-0 mt-1 text-[17px] font-semibold text-text-1">{d.nextWeekProposal?.kind==="keep_current"?"Keep the system stable while calibration continues.":"Carry the evidence-based adjustment into Week 2."}</h3><div className="mt-3 grid gap-2">{d.nextWeekProposal?.changes?.length?d.nextWeekProposal.changes.map((change:string)=><div key={change} className="rounded-xl border border-white/[.06] px-3 py-2 text-[11.5px] text-text-2">{change}</div>):<div className="rounded-xl border border-white/[.06] px-3 py-2 text-[11.5px] text-text-2">No live-system changes proposed.</div>}</div><div className="mt-4 grid grid-cols-2 gap-2"><form action={resolveNextWeekAction}><input type="hidden" name="resolution" value="approved"/><button className="py-liquid-button min-h-11 w-full" type="submit">Approve next week</button></form><form action={resolveNextWeekAction}><input type="hidden" name="resolution" value="keep_current"/><button className="min-h-11 w-full rounded-[14px] border border-white/[.08] px-3 text-[11px] font-semibold text-text-2" type="submit">Keep current system</button></form></div><Link href="/coach" className="mt-2 inline-flex min-h-11 items-center text-[11px] font-semibold text-text-3">Edit with Coach</Link><form action={resolveNextWeekAction} className="mt-2"><input type="hidden" name="resolution" value="deferred"/><button className="min-h-11 w-full text-[11px] font-semibold text-text-3" type="submit">Decide later</button></form></div>}
  </section>;
}

function ActionRow({action,index}:{action:PlannedResetAction;index:number}){return <div className="py-glass-soft flex items-center gap-3 p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white/[.04] text-[10px] font-bold text-text-3">0{index+1}</span><div className="min-w-0 flex-1"><div className="text-[13px] font-semibold text-text-1">{action.title}</div><div className="mt-1 text-[10.5px] text-text-3">{action.durationMinutes?`${action.durationMinutes} min · `:""}{action.completed?"Completed":"Real action from your approved system"}</div></div><span className={`h-2.5 w-2.5 rounded-full ${action.completed?"bg-emerald-400":"border border-white/25"}`}/></div>}
function MiniAction({action,label}:{action:PlannedResetAction;label?:string}){return <div className="flex items-start gap-2 rounded-[12px] border border-white/[.055] bg-white/[.02] px-3 py-2.5"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-accent/60"/><div className="text-[11.5px] leading-relaxed text-text-2">{label??action.title}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-[14px] border border-white/[.06] bg-white/[.025] p-3"><div className="text-[9.5px] font-semibold uppercase tracking-[.12em] text-text-3">{label}</div><div className="mt-1 text-[13px] font-semibold text-text-1">{value}</div></div>}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-[9.5px] font-semibold uppercase tracking-[.11em] text-text-3">{label}</div><div className="mt-1 text-[11.5px] leading-relaxed text-text-2">{value}</div></div>}
function ReviewBlock({title,lines}:{title:string;lines:string[]}){return <div className="rounded-[14px] border border-white/[.06] bg-white/[.025] p-3"><div className="text-[12px] font-semibold text-text-1">{title}</div><div className="mt-2 grid gap-1">{lines.map((line,index)=><div key={`${line}-${index}`} className="text-[11px] leading-relaxed text-text-3">{line}</div>)}</div></div>}
