import { getProfile } from "@/lib/data/profile";
import { userDate } from "@/lib/health/schedule";
import Link from "next/link";
import { addWorkout, completeWorkoutPlanSession, confirmWorkoutPlanRecommendation, generateWorkoutPlan } from "@/lib/actions/fitness";
import { setRecommendationState } from "@/lib/actions/recommendations";
import { createClient } from "@/lib/supabase/server";

type Exercise={name:string;sets:string;reps:string;rest?:string};
type Session={key:string;day:string;dayIndex:number;title:string;focus:string;duration:number;exercises:Exercise[]};
type WorkoutPlan={id:string;title:string;goal:string;days_per_week:number;session_minutes:number;experience:string;schedule:Session[]|null;source:string};
const DAYS=[{i:1,s:"Mon",l:"Monday"},{i:2,s:"Tue",l:"Tuesday"},{i:3,s:"Wed",l:"Wednesday"},{i:4,s:"Thu",l:"Thursday"},{i:5,s:"Fri",l:"Friday"},{i:6,s:"Sat",l:"Saturday"},{i:0,s:"Sun",l:"Sunday"}];

export default async function FitnessPage(){
 const supabase=await createClient();const profile=await getProfile();const today=userDate(new Date(),profile.timezone);
 const [{data:planData},{data:planLogs},{data:workouts},{data:proposalData}]=await Promise.all([
  supabase.from("workout_plans").select("id,title,goal,days_per_week,session_minutes,experience,schedule,source").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  supabase.from("workout_plan_logs").select("plan_id,session_key,completed_on").eq("status","completed").gte("completed_on",weekStart()),
  supabase.from("workouts").select("id,title,type,duration_minutes,performed_at,source").order("performed_at",{ascending:false}).limit(6),
  supabase.from("ai_recommendations").select("id,observation,suggested_action,expected_impact,confidence,status,action_payload,created_at").eq("action_type","workout_plan.activate").in("status",["pending","accepted"]).order("created_at",{ascending:false}).limit(1).maybeSingle()
 ]);
 const plan=(planData as WorkoutPlan|null)??null;const proposal=proposalData as null|{id:string;observation:string;suggested_action:string;expected_impact:string|null;confidence:string;status:string;action_payload:{title?:string;schedule?:Session[]}};const proposedSchedule=Array.isArray(proposal?.action_payload?.schedule)?proposal!.action_payload.schedule:[];const schedule=Array.isArray(plan?.schedule)?plan!.schedule!:[];const selected=new Set(schedule.map(x=>x.dayIndex));const todaySession=schedule.find(x=>x.dayIndex===new Date(`${today}T12:00:00Z`).getUTCDay())??null;const completedToday=todaySession?(planLogs??[]).some(log=>log.plan_id===plan?.id&&log.session_key===todaySession.key&&log.completed_on===today):false;const completedThisWeek=(planLogs??[]).filter(log=>log.plan_id===plan?.id).length;
 return <main className="py-mobile-shell md:py-shell-narrow">
  <header className="mb-6"><div className="flex items-center justify-between gap-4"><div><h1 className="m-0 text-[30px] font-bold tracking-[-.045em] text-text-1">Training</h1><p className="m-0 mt-2 max-w-[560px] text-[13px] leading-relaxed text-text-2">Your actual workout plan, built around the days you can consistently train.</p></div><Link href="/reminders" className="py-glass-pill">Reminders</Link></div></header>

  {plan&&<section className="py-glass-hero p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-semibold text-text-3">Active plan</div><h2 className="m-0 mt-1.5 text-[25px] font-bold tracking-[-.04em] text-text-1">{plan.title}</h2><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">{plan.goal}</p></div><span className="py-glass-pill">{completedThisWeek}/{plan.days_per_week} this week</span></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{DAYS.map(day=><div key={day.i} className={`min-w-[50px] rounded-[15px] border px-2 py-3 text-center ${selected.has(day.i)?"border-accent bg-accent-soft":"border-border bg-surface/40"}`}><div className={`text-[10px] font-semibold ${selected.has(day.i)?"text-accent-text":"text-text-3"}`}>{day.s}</div><div className="mt-1 text-[8px] text-text-3">{selected.has(day.i)?"train":"off"}</div></div>)}</div></section>}

  {todaySession?<section className="py-glass-soft mt-4 p-5"><div className="flex items-center justify-between"><div className="text-[11px] font-semibold text-accent-text">Today</div><span className="py-glass-pill">{completedToday?"Complete":`${todaySession.duration} min`}</span></div><h2 className="m-0 mt-2 text-[22px] font-semibold tracking-[-.03em] text-text-1">{todaySession.title}</h2><p className="m-0 mt-1 text-[11.5px] text-text-3">{todaySession.focus}</p><div className="mt-4 space-y-2">{todaySession.exercises.map((e,i)=><div key={`${e.name}-${i}`} className="flex items-center gap-3 rounded-[14px] border border-border bg-surface/40 px-3 py-2.5"><span className="min-w-0 flex-1 text-[12px] font-medium text-text-1">{e.name}</span><span className="text-[10px] text-text-3">{e.sets} × {e.reps}</span></div>)}</div>{!completedToday?<form action={completeWorkoutPlanSession.bind(null,plan!.id,todaySession.key,todaySession.duration)}><button className="py-liquid-button mt-4 w-full">Complete workout</button></form>:<div className="mt-4 rounded-[14px] border border-positive/20 bg-positive-soft px-4 py-3 text-center text-[12px] font-semibold text-positive">Workout complete</div>}</section>:plan?<section className="py-glass-soft mt-4 p-4"><div className="text-[13px] font-semibold text-text-1">Recovery day</div><div className="mt-1 text-[11px] text-text-3">No programmed workout today.</div></section>:null}

  {proposal&&<section className="py-glass-hero mt-5 p-5"><div className="flex items-center justify-between gap-3"><div className="text-[11px] font-semibold text-accent-text">Plan ready for review</div><span className="py-glass-pill">{proposal.confidence} confidence</span></div><h2 className="m-0 mt-2 text-[21px] font-semibold tracking-[-.03em] text-text-1">{proposal.action_payload.title??"Proposed workout plan"}</h2><p className="m-0 mt-2 text-[12px] leading-relaxed text-text-2">{proposal.observation}</p><div className="mt-4 space-y-2">{proposedSchedule.map(session=><div key={session.key} className="rounded-[14px] border border-border bg-surface/40 px-3 py-2.5"><div className="flex items-center justify-between gap-3"><span className="text-[12px] font-semibold text-text-1">{session.day} · {session.title}</span><span className="text-[10px] text-text-3">{session.duration}m</span></div><div className="mt-1 text-[10.5px] text-text-3">{session.focus}</div></div>)}</div><p className="m-0 mt-3 text-[11px] text-text-3">{proposal.expected_impact}</p><div className="mt-4 grid grid-cols-2 gap-2.5"><form action={setRecommendationState.bind(null,proposal.id,"dismissed")}><button className="py-button-secondary w-full">Dismiss</button></form><form action={confirmWorkoutPlanRecommendation.bind(null,proposal.id)}><button className="py-liquid-button w-full">Activate plan</button></form></div></section>}

  <section className="mt-6"><div className="mb-3"><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">{plan?"Edit your training week":"Build your training week"}</h2><p className="m-0 mt-1 text-[11px] text-text-3">Pick exact days. Monday / Wednesday / Friday works exactly as selected.</p></div><form action={generateWorkoutPlan} className="py-glass-soft p-4"><input name="goal" required defaultValue={plan?.goal??"Build muscle and improve body composition"} className="py-input" placeholder="Primary fitness goal"/><div className="mt-3 grid grid-cols-7 gap-1.5">{DAYS.map(day=><label key={day.i} className="cursor-pointer"><input className="peer sr-only" type="checkbox" name="trainingDays" value={day.i} defaultChecked={selected.size?selected.has(day.i):[1,3,5].includes(day.i)}/><span className="flex min-h-[48px] items-center justify-center rounded-[13px] border border-border bg-surface text-[9px] font-semibold text-text-3 transition peer-checked:border-accent peer-checked:bg-accent-soft peer-checked:text-accent-text">{day.s}</span></label>)}</div><div className="mt-3 grid grid-cols-2 gap-2.5"><select name="experience" defaultValue={plan?.experience??"intermediate"} className="py-input text-[12px]"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><select name="minutes" defaultValue={String(plan?.session_minutes??50)} className="py-input text-[12px]"><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option><option value="75">75 min</option></select></div><button className="py-liquid-button mt-3 w-full">{plan?"Rebuild around these days":"Build my workout plan"}</button></form></section>

  {schedule.length>0&&<section className="mt-6"><h2 className="m-0 mb-3 text-[20px] font-semibold tracking-[-.03em] text-text-1">Week plan</h2><div className="space-y-2.5">{schedule.sort((a,b)=>((a.dayIndex+6)%7)-((b.dayIndex+6)%7)).map(s=><div key={s.key} className="py-glass-soft p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-semibold text-accent-text">{s.day}</div><div className="mt-1 text-[14px] font-semibold text-text-1">{s.title}</div><div className="mt-1 text-[10.5px] text-text-3">{s.focus}</div></div><span className="py-glass-pill">{s.duration}m</span></div></div>)}</div></section>}

  <section className="mt-6"><details className="py-glass-soft p-4"><summary className="cursor-pointer text-[13px] font-semibold text-text-1">Log a different workout</summary><form action={addWorkout} className="mt-3 space-y-2.5"><input name="title" required placeholder="Workout title" className="py-input"/><div className="grid grid-cols-2 gap-2.5"><select name="type" className="py-input text-[12px]" defaultValue="strength"><option value="strength">Strength</option><option value="cardio">Cardio</option><option value="mobility">Mobility</option><option value="sport">Sport</option></select><input name="duration" type="number" min="1" required placeholder="Minutes" className="py-input"/></div><button className="py-button-secondary w-full">Log workout</button></form></details></section>
 </main>
}
function weekStart(){const date=new Date();const day=date.getDay();date.setDate(date.getDate()+(day===0?-6:1-day));return date.toISOString().slice(0,10)}
