import { addWorkout, completeWorkoutPlanSession, generateWorkoutPlan } from "@/lib/actions/fitness";
import { createClient } from "@/lib/supabase/server";

type Exercise = { name: string; sets: string; reps: string; rest?: string };
type Session = { key: string; day: string; dayIndex: number; title: string; focus: string; duration: number; exercises: Exercise[] };

type WorkoutPlan = {
  id: string;
  title: string;
  goal: string;
  days_per_week: number;
  session_minutes: number;
  experience: string;
  schedule: Session[] | null;
  source: string;
};

export default async function FitnessPage() {
  const supabase = await createClient();
  const today = new Date().toISOString().slice(0, 10);
  const [{ data: planData }, { data: planLogs }, { data: workouts }] = await Promise.all([
    supabase.from("workout_plans").select("id,title,goal,days_per_week,session_minutes,experience,schedule,source").eq("active", true).order("created_at", { ascending: false }).limit(1).maybeSingle(),
    supabase.from("workout_plan_logs").select("plan_id,session_key,completed_on").gte("completed_on", weekStart()),
    supabase.from("workouts").select("id,title,type,duration_minutes,performed_at,source").order("performed_at", { ascending: false }).limit(10),
  ]);
  const plan = (planData as WorkoutPlan | null) ?? null;
  const schedule = Array.isArray(plan?.schedule) ? plan!.schedule! : [];
  const todaySession = schedule.find((item) => item.dayIndex === new Date().getDay()) ?? null;
  const completedToday = todaySession ? (planLogs ?? []).some((log) => log.plan_id === plan?.id && log.session_key === todaySession.key && log.completed_on === today) : false;
  const completedThisWeek = (planLogs ?? []).filter((log) => log.plan_id === plan?.id).length;

  return <main className="py-mobile-shell md:py-shell-narrow">
    <header className="py-animate-in mb-7 flex items-start justify-between gap-4"><div><div className="py-eyebrow text-accent-text">Adaptive training</div><h1 className="py-title">Fitness</h1><p className="py-subtitle">Build a plan around your goal, available days, and session length. Your scheduled workout automatically becomes part of Dashboard.</p></div><span className="py-glass-pill text-accent-text">AI-assisted</span></header>

    {plan ? <>
      <section className="py-glass-hero py-animate-in py-stagger-1 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="py-eyebrow text-[#C8AEFF]">Active program</div><h2 className="m-0 mt-2 text-[25px] font-bold tracking-[-.04em] text-white">{plan.title}</h2><p className="m-0 mt-2 text-[12.5px] leading-relaxed text-[#C2BED0]">{plan.goal}</p></div><span className="py-glass-pill text-[#C8AEFF]">{plan.days_per_week}× / week</span></div><div className="mt-5 grid grid-cols-3 gap-2"><MiniStat label="This week" value={`${completedThisWeek}/${plan.days_per_week}`} /><MiniStat label="Session" value={`${plan.session_minutes}m`} /><MiniStat label="Level" value={plan.experience} /></div></section>

      {todaySession ? <section className="py-orbit-card py-animate-in py-stagger-2 mt-4 p-5"><div className="flex items-center justify-between gap-3"><div className="py-eyebrow text-accent-text">Today’s training</div><span className={`py-glass-pill ${completedToday ? "text-positive" : "text-[#C8AEFF]"}`}>{completedToday ? "Complete" : `${todaySession.duration} min`}</span></div><h2 className="m-0 mt-3 text-[24px] font-bold tracking-[-.035em] text-text-1">{todaySession.title}</h2><p className="m-0 mt-1.5 text-[12px] leading-relaxed text-text-2">{todaySession.focus}</p><div className="mt-4 space-y-2">{todaySession.exercises.map((exercise, index) => <ExerciseRow key={`${exercise.name}-${index}`} exercise={exercise} />)}</div>{!completedToday ? <form action={completeWorkoutPlanSession.bind(null, plan.id, todaySession.key, todaySession.duration)}><button className="py-liquid-button mt-5 w-full">Complete today’s workout</button></form> : <div className="mt-5 rounded-[16px] border border-positive/20 bg-positive-soft px-4 py-3 text-center text-[12px] font-semibold text-positive">Workout logged to your Dashboard score</div>}</section> : <section className="py-glass-soft py-animate-in py-stagger-2 mt-4 p-4"><div className="py-eyebrow text-accent-text">Recovery day</div><div className="mt-2 text-[17px] font-semibold text-text-1">No programmed lifting today.</div><p className="m-0 mt-1.5 text-[11.5px] leading-relaxed text-text-3">Use the open space for recovery, walking, mobility, or the priorities on your Dashboard.</p></section>}

      <section className="py-animate-in py-stagger-3 mt-7"><div className="mb-3"><div className="py-eyebrow">Program map</div><h2 className="m-0 mt-1 text-[22px] font-semibold tracking-[-.03em] text-text-1">Your week</h2></div><div className="grid gap-3">{schedule.map((session) => <div key={session.key} className="py-glass-soft p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-[.13em] text-accent-text">{session.day}</div><div className="mt-1 text-[15px] font-semibold text-text-1">{session.title}</div><div className="mt-1 text-[11px] text-text-3">{session.focus}</div></div><span className="py-glass-pill">{session.duration}m</span></div><div className="mt-3 flex flex-wrap gap-1.5">{session.exercises.slice(0, 5).map((exercise, index) => <span key={`${exercise.name}-${index}`} className="rounded-full border border-white/[.06] bg-white/[.025] px-2.5 py-1 text-[9.5px] text-text-3">{exercise.name}</span>)}</div></div>)}</div></section>
    </> : <section className="py-glass-hero py-animate-in py-stagger-1 p-5 sm:p-6"><div className="py-eyebrow text-[#C8AEFF]">Build your training system</div><h2 className="m-0 mt-3 text-[26px] font-bold leading-[1.08] tracking-[-.04em] text-white">Tell Project You+ what you want. It builds the week.</h2><p className="m-0 mt-2 text-[12.5px] leading-relaxed text-[#C2BED0]">Choose your goal and how many days you can consistently train. The plan stays editable and every scheduled session feeds Dashboard.</p></section>}

    <form action={generateWorkoutPlan} className="py-glass-soft py-animate-in py-stagger-4 mt-5 p-4"><div className="py-eyebrow text-accent-text">{plan ? "Rebuild plan" : "AI plan builder"}</div><div className="mt-3 space-y-2.5"><input name="goal" required defaultValue={plan?.goal ?? "Build muscle and improve body composition"} className="py-input" placeholder="Primary fitness goal"/><div className="grid grid-cols-2 gap-2.5"><select name="days" defaultValue={String(plan?.days_per_week ?? 4)} className="py-input text-[12px]"><option value="2">2 days / week</option><option value="3">3 days / week</option><option value="4">4 days / week</option><option value="5">5 days / week</option><option value="6">6 days / week</option></select><select name="experience" defaultValue={plan?.experience ?? "intermediate"} className="py-input text-[12px]"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div><select name="minutes" defaultValue={String(plan?.session_minutes ?? 50)} className="py-input text-[12px]"><option value="30">About 30 minutes</option><option value="45">About 45 minutes</option><option value="60">About 60 minutes</option><option value="75">About 75 minutes</option></select></div><button className="py-liquid-button mt-3 w-full">{plan ? "Generate a new plan" : "Build my workout plan"}</button><p className="m-0 mt-2 text-center text-[10px] leading-relaxed text-text-3">General fitness planning only. Adjust exercises for your equipment, experience, and any professional guidance you follow.</p></form>

    <section className="py-animate-in py-stagger-5 mt-7"><div className="mb-3"><div className="py-eyebrow">Flexible logging</div><h2 className="m-0 mt-1 text-[22px] font-semibold tracking-[-.03em] text-text-1">Did something different?</h2></div><form action={addWorkout} className="py-glass-soft p-4"><div className="space-y-2.5"><input name="title" required placeholder="Workout title" className="py-input"/><div className="grid grid-cols-2 gap-2.5"><select name="type" className="py-input text-[12px]" defaultValue="strength"><option value="strength">Strength</option><option value="cardio">Cardio</option><option value="mobility">Mobility</option><option value="sport">Sport</option></select><input name="duration" type="number" min="1" required placeholder="Minutes" className="py-input"/></div></div><button className="py-button-secondary mt-3 w-full">Log unplanned workout</button></form>{(workouts ?? []).length > 0 ? <div className="py-glass-soft mt-3 divide-y divide-white/[.06] px-4">{(workouts ?? []).slice(0, 5).map((workout) => <div key={workout.id} className="flex items-center gap-3 py-3.5"><span className="py-empty-icon">↗</span><span className="min-w-0 flex-1"><span className="block text-[13px] font-semibold text-text-1">{workout.title}</span><span className="mt-0.5 block text-[10.5px] capitalize text-text-3">{workout.type ?? "workout"} · {new Date(workout.performed_at).toLocaleDateString()}</span></span><span className="text-[11px] font-semibold text-text-2">{workout.duration_minutes ?? 0}m</span></div>)}</div> : null}</section>
  </main>;
}

function ExerciseRow({ exercise }: { exercise: Exercise }) { return <div className="flex items-center gap-3 rounded-[14px] border border-white/[.06] bg-white/[.025] px-3 py-2.5"><span className="min-w-0 flex-1 text-[12px] font-medium text-text-1">{exercise.name}</span><span className="text-[10px] text-text-3">{exercise.sets} × {exercise.reps}</span><span className="w-[50px] text-right text-[9.5px] text-text-3">{exercise.rest}</span></div>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="rounded-[16px] border border-white/[.08] bg-white/[.035] p-3"><div className="text-[9px] uppercase tracking-[.12em] text-[#9E97AC]">{label}</div><div className="mt-1 text-[13px] font-semibold capitalize text-white">{value}</div></div>; }
function weekStart() { const date = new Date(); const day = date.getDay(); const diff = day === 0 ? -6 : 1 - day; date.setDate(date.getDate() + diff); return date.toISOString().slice(0, 10); }
