import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { EMPTY_ANSWERS, sanitizeAnswers } from "../lib/onboarding/schema";
import { findExistingSystemMatches } from "../lib/onboarding/system-existing";
import { repairSystemProposal } from "../lib/onboarding/system-repair";
import { SYSTEM_GENERATOR_VERSION, type SystemProposal } from "../lib/onboarding/system-schema";

function answers(){return sanitizeAnswers({...EMPTY_ANSWERS,direction:{domains:["money"],primaryDomain:"money"},friction:{categories:["spending"],note:""},goals:[{clientId:"source-money",raw:"Save $10,000",title:"Save $10,000",domain:"money",desiredOutcome:"Save $10,000",measurableTarget:"$10,000",targetDate:null,why:null,priority:1,status:"draft",rationale:null}],finance:{deferred:false,primaryGoal:"save_for_purchase",secondaryGoals:[],optionalDetail:""},coaching:{style:"balanced",checkInFrequency:"daily",checkInWindow:"morning",weeklyReviewDay:0,weeklyReviewTime:"18:00",reminderIntent:true}});}

function proposal():SystemProposal{return {
  metadata:{proposalId:"p-hardening",userId:"00000000-0000-0000-0000-000000000001",onboardingSessionId:"00000000-0000-0000-0000-000000000002",sourceContextVersion:"ctx",generatorVersion:SYSTEM_GENERATOR_VERSION,createdAt:"2026-09-12T12:00:00.000Z",status:"awaiting_confirmation",confidence:"medium",missingInformation:[],validationVersion:"v3"},
  goals:[{clientId:"goal-money",sourceGoalClientId:"source-money",sourceOnboardingGoal:"Save $10,000",domain:"money",title:"Save $10,000",desiredOutcome:"Save $10,000",measurableTarget:"$10,000",targetValue:10000,targetUnit:"USD",targetDate:null,currentValue:null,priority:1,successMetrics:[{id:"metric-money",name:"Savings balance",unit:"USD",direction:"increase",type:"outcome",entryFrequency:"monthly",dataSource:"finance",baseline:null,targetValue:10000,targetLabel:"Reach $10,000",needsConfirmation:false}],milestones:[{id:"milestone-money",title:"Reach savings target",targetValue:10000,unit:"USD",targetDate:null,order:1}],rationale:"Use confirmed finance context.",frictionResponse:"Review controllable spending.",deferred:false}],
  actions:[{clientId:"action-goal-money-spend",linkedGoalClientId:"goal-money",domain:"money",kind:"review",title:"Review discretionary spending for the last 7 days",frequency:"weekly",targetPerWeek:1,preferredDays:[0],preferredTime:null,durationMinutes:15,trigger:"Weekly Review",minimumVersion:"Review one category.",recoveryRule:"Resume next week.",evidenceType:"financial_review_completed",startingDifficulty:"easy",firstDueDate:null,rationale:"Observe before setting a limit.",deferred:false},{clientId:"action-goal-money-month",linkedGoalClientId:"goal-money",domain:"money",kind:"recurring_action",title:"Complete a monthly savings checkpoint",frequency:"weekly",targetPerWeek:1,preferredDays:[0],preferredTime:null,durationMinutes:5,trigger:"First Weekly Review of the month",minimumVersion:"Record the balance.",recoveryRule:"Resume next month.",evidenceType:"metric_recorded",startingDifficulty:"easy",firstDueDate:null,rationale:"Keep the outcome visible.",deferred:false}],
  schedule:[],metrics:[{id:"metric-money",name:"Savings balance",unit:"USD",direction:"increase",type:"outcome",entryFrequency:"monthly",dataSource:"finance",baseline:null,targetValue:10000,targetLabel:"Reach $10,000",needsConfirmation:false,linkedGoalClientId:"goal-money"}],
  weeklyReview:{day:0,time:"18:00",reminderIntent:true,rationale:"Adjust from evidence.",goalCheckpointFrequency:"weekly",healthCheckIn:false,financeCheckIn:true,questions:["What changed?"]},today:{firstMeaningfulActionClientId:"action-goal-money-spend",priorityActionClientIds:["action-goal-money-spend"],habitActionClientIds:[],coachOpeningMessage:"Start simple."},workload:{weeklyMinutes:20,dailyHabitCount:0,weeklyActionCount:2,scheduledSessionCount:0,activeGoalCount:1,phased:false,phaseLabel:"Week 1",bufferPreserved:true,reductions:[]},frictionSummary:"Spending review keeps the plan controllable.",activationWarnings:[],generationVersion:SYSTEM_GENERATOR_VERSION,generatedAt:"2026-09-12T12:00:00.000Z",status:"draft",habits:[],priorities:[{clientId:"action-goal-money-spend",title:"Review discretionary spending for the last 7 days",goalClientId:"goal-money",dueWindow:"today",rationale:"Observe before setting a limit."}],healthPlan:null,financialFocus:{title:"Save $10,000",action:"Review discretionary spending for the last 7 days",goalType:"save_for_purchase",rationale:"Missing timeline.",targetAmount:10000,currentAmount:null,monthlyTarget:null,weeklyEquivalent:null,calculation:null}
};}

test("existing goals and habits are detected by the same normalized-title rule used for duplicate protection",()=>{const p=proposal();p.actions.push({clientId:"habit-one",linkedGoalClientId:"goal-money",domain:"money",kind:"habit",title:"Check spending plan",frequency:"weekly",targetPerWeek:1,preferredDays:[0],preferredTime:null,durationMinutes:3,trigger:null,minimumVersion:null,recoveryRule:null,evidenceType:"habit_logged",startingDifficulty:"easy",firstDueDate:null,rationale:"test",deferred:false});const matches=findExistingSystemMatches(p,[{id:"g1",title:"  save   $10,000 ",status:"active"},{id:"g2",title:"Save $10,000",status:"paused"}],[{id:"h1",title:"check SPENDING plan"}]);assert.deepEqual(matches.map(match=>[match.kind,match.existingId]),[["goal","g1"],["habit","h1"]]);});

test("finance monthly checkpoint is review cadence, never a fake weekly task",()=>{const repaired=repairSystemProposal(proposal(),answers());assert.equal(repaired.actions.some(action=>action.clientId.endsWith("-month")),false);assert.deepEqual(repaired.weeklyReview.goalCheckpoints,[{linkedGoalClientId:"goal-money",frequency:"monthly",label:"Monthly financial progress checkpoint"}]);assert.ok(repaired.metadata.missingInformation.some(item=>item.key.includes("finance_target_date")));assert.equal(repaired.actions.some(action=>action.clientId.endsWith("-save")),false);});

test("confirmed savings inputs deterministically create the contribution pace and clear missing-input warnings",()=>{const p=proposal();p.goals[0].currentValue=1000;p.goals[0].targetDate="2027-09-12";const repaired=repairSystemProposal(p,answers());const contribution=repaired.actions.find(action=>action.clientId.endsWith("-save"));assert.ok(contribution);assert.match(contribution?.title??"",/per week/i);assert.ok((repaired.financialFocus?.monthlyTarget??0)>0);assert.ok((repaired.financialFocus?.weeklyEquivalent??0)>0);assert.match(repaired.financialFocus?.calculation??"",/remaining.*month/i);assert.equal(repaired.metadata.missingInformation.some(item=>item.domain==="money"),false);assert.equal(repaired.goals[0].successMetrics[0].baseline,1000);assert.equal(repaired.goals[0].milestones[0].targetDate,"2027-09-12");});

test("proposal UI exposes explicit remove, duplicate-connect, and deterministic finance scenario controls",()=>{const source=readFileSync(new URL("../components/onboarding/system-proposal-hardening-controls.tsx",import.meta.url),"utf8");assert.match(source,/Connect existing/);assert.match(source,/>Remove</);assert.match(source,/6,12,18/);assert.match(source,/Apply finance details/);assert.match(source,/goal_edited/);assert.doesNotMatch(source,/move money automatically/i);});
