import assert from "node:assert/strict";
import test from "node:test";
import { calculateProgression, detectIntegrityFlags, stageForLevel, type ProgressionSnapshot } from "../lib/progression/calculator";
import { ACHIEVEMENTS, qualifyAchievements } from "../lib/progression/achievements";
import { PROGRESSION_CONFIG } from "../lib/progression/config";

const NOW = new Date("2026-09-11T12:00:00.000Z");
const day = (offset: number) => { const value = new Date(NOW); value.setUTCDate(value.getUTCDate() - offset); return value.toISOString().slice(0, 10); };
const snapshots = (count: number, score = 90, domains: Record<string,number> = { health: 90, finance: 90, productivity: 90 }): ProgressionSnapshot[] => Array.from({ length: count }, (_, index) => ({ date: day(count - index - 1), score, coveragePct: 90, domains }));

test("progression smooths score across 7, 28, and 90-day horizons", () => { const rows = snapshots(90, 80); rows.splice(-7, 7, ...snapshots(7, 100)); const result = calculateProgression({ snapshots: rows, activityDays: rows.map((row) => row.date), tasks: [], now: NOW }); assert.equal(result.averages.days7, 100); assert.equal(result.averages.days90, 82); assert.ok(result.level < 100); });
test("balanced domains score above a similarly averaged imbalanced set", () => { const balanced = calculateProgression({ snapshots: snapshots(90, 90), activityDays: snapshots(90).map((row) => row.date), tasks: [], now: NOW }); const uneven = calculateProgression({ snapshots: snapshots(90, 90, { health: 100, finance: 50, productivity: 100 }), activityDays: snapshots(90).map((row) => row.date), tasks: [], now: NOW }); assert.ok((balanced.domainBalance ?? 0) > (uneven.domainBalance ?? 0)); assert.ok(balanced.level > uneven.level); });
test("insufficient history caps advancement and reports calibration", () => { const result = calculateProgression({ snapshots: snapshots(1, 100, { health: 100, finance: 100, productivity: 100 }), activityDays: [day(0)], tasks: [], now: NOW }); assert.equal(result.status, "calibrating"); assert.equal(result.evidenceCap, 59); assert.ok(result.level <= 59); });
test("milestone stage and next milestone follow the approved sequence", () => { assert.equal(stageForLevel(69), "Foundation"); assert.equal(stageForLevel(70), "Momentum"); assert.equal(stageForLevel(80), "Alignment"); assert.deepEqual(PROGRESSION_CONFIG.milestones.map((item) => item.level), [60, 70, 80, 90, 99]); const result = calculateProgression({ snapshots: snapshots(28, 75), activityDays: snapshots(28).map((row) => row.date), tasks: [], now: NOW }); assert.equal(result.nextMilestone?.level, 80); });
test("one perfect day can never qualify for 1%", () => { const result = calculateProgression({ snapshots: snapshots(1, 100, { health: 100, finance: 100, productivity: 100 }), activityDays: [day(0)], tasks: [], now: NOW }); assert.equal(result.qualifiesForOnePercent, false); assert.ok(result.level < 60); });
test("strong balanced 90-day evidence qualifies for 1%", () => { const rows = snapshots(90, 98, { health: 97, finance: 96, productivity: 98, goals: 97 }); const result = calculateProgression({ snapshots: rows, activityDays: rows.map((row) => row.date), tasks: [], now: NOW }); assert.equal(result.qualifiesForOnePercent, true); assert.equal(result.level, 99); assert.equal(result.stage, "1%"); });
test("a weak active domain prevents 1%", () => { const rows = snapshots(90, 98, { health: 99, finance: 60, productivity: 99 }); const result = calculateProgression({ snapshots: rows, activityDays: rows.map((row) => row.date), tasks: [], now: NOW }); assert.equal(result.qualifiesForOnePercent, false); assert.ok(result.limitingFactors.some((item) => item.includes("Lowest active domain"))); });
test("integrity signals block trivial task farming", () => { const tasks = Array.from({ length: 15 }, (_, index) => ({ title: `Tiny ${index}`, tier: "optional", createdAt: `${day(0)}T12:00:${String(index).padStart(2, "0")}.000Z`, completedAt: `${day(0)}T12:00:${String(index + 1).padStart(2, "0")}.000Z` })); assert.ok(detectIntegrityFlags(tasks, NOW).includes("excessive_trivial_tasks")); const rows = snapshots(90, 100, { health: 100, finance: 100, productivity: 100 }); assert.equal(calculateProgression({ snapshots: rows, activityDays: rows.map((row) => row.date), tasks, now: NOW }).qualifiesForOnePercent, false); });
test("decline is gradual and a historical 1% can be represented separately from current qualification", () => { const result = calculateProgression({ snapshots: snapshots(90, 45), activityDays: snapshots(30).map((row) => row.date), tasks: [], previousLevel: 99, previousCalculatedOn: day(1), now: NOW }); assert.equal(result.level, 98); assert.equal(result.qualifiesForOnePercent, false); });

test("all core achievements qualify from provable evidence with earliest dates", () => {
  const active = Array.from({ length: 35 }, (_, index) => { const value = new Date("2026-08-03T12:00:00Z"); value.setUTCDate(value.getUTCDate() + index); return value.toISOString().slice(0, 10); });
  const earned = qualifyAchievements({ activeDays: active.slice(0, 30), goalCompletions: ["2026-08-20T10:00:00Z"], workoutDays: ["2026-08-03", "2026-08-05", "2026-08-07"], reviewDates: ["2026-08-09T18:00:00Z"], onTargetBudgetMonths: ["2026-07"], profileCreatedAt: "2026-07-01T12:00:00Z", now: NOW });
  const keys = new Set(earned.map((item) => item.key)); for (const definition of ACHIEVEMENTS) assert.ok(keys.has(definition.key), definition.key);
  assert.equal(earned.find((item) => item.key === "first_day_completed")?.earnedAt.slice(0, 10), "2026-08-03");
});
test("achievement definitions and qualified results are duplicate-free", () => { assert.equal(new Set(ACHIEVEMENTS.map((item) => item.key)).size, ACHIEVEMENTS.length); const facts = { activeDays: Array.from({length:7},(_,index)=>day(index)), goalCompletions:[], workoutDays:[], reviewDates:[], onTargetBudgetMonths:[], profileCreatedAt:null }; const result = qualifyAchievements(facts); assert.equal(new Set(result.map((item) => item.key)).size, result.length); });
