import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { addSupplement, logSupplementToday, setSupplementActive } from "@/lib/actions/supplements";

const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export default async function SupplementsPage(){
 const supabase=await createClient();const today=new Date().toISOString().slice(0,10);const dayIndex=new Date().getDay();
 const [{data:supplements},{data:logs}]=await Promise.all([
  supabase.from("supplements").select("id,name,dosage,timing,frequency,notes,active").order("created_at"),
  supabase.from("supplement_logs").select("supplement_id,logged_on").eq("logged_on",today)
 ]);
 const rows=supplements??[];const logged=new Set((logs??[]).map(r=>r.supplement_id));const active=rows.filter(r=>r.active);const due=active.filter(r=>isDue(r.frequency,dayIndex));const done=due.filter(r=>logged.has(r.id)).length;
 return <main className="py-mobile-shell md:py-shell-narrow">
  <header className="mb-6"><div className="flex items-center justify-between gap-4"><div><h1 className="m-0 text-[30px] font-bold tracking-[-.045em] text-text-1">Supplements</h1><p className="m-0 mt-2 max-w-[560px] text-[13px] leading-relaxed text-text-2">A simple checklist for what you already choose to take, on the days you actually take it.</p></div><Link href="/reminders" className="py-glass-pill">Add reminder</Link></div></header>

  <section className="py-glass-hero p-5"><div className="flex items-end justify-between gap-4"><div><div className="text-[11px] font-semibold text-text-3">Today’s protocol</div><div className="mt-1 text-[34px] font-bold tracking-[-.05em] text-text-1">{done}/{due.length}</div><div className="mt-1 text-[11px] text-text-3">scheduled for {DAYS[dayIndex]}</div></div><div className="text-right text-[11px] text-text-3">{due.length?Math.round(done/due.length*100):0}% complete</div></div></section>

  <section className="mt-5"><div className="mb-3 flex items-end justify-between"><div><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">Today’s checklist</h2><p className="m-0 mt-1 text-[10.5px] text-text-3">Only items scheduled for today appear here.</p></div></div>{due.length?<div className="py-glass-soft divide-y divide-border px-4">{due.map(item=>{const checked=logged.has(item.id);return <div key={item.id} className="flex items-center gap-3 py-4"><form action={logSupplementToday.bind(null,item.id)}><button disabled={checked} className={`py-check ${checked?"py-check-done":""}`}>{checked?"✓":""}</button></form><div className="min-w-0 flex-1"><div className={`text-[14px] font-semibold ${checked?"text-text-3 line-through":"text-text-1"}`}>{item.name}</div><div className="mt-0.5 text-[10.5px] capitalize text-text-3">{item.dosage||"Dose not set"} · {item.timing.replaceAll("_"," ")}</div></div><Link href="/reminders" className="text-[10px] font-semibold text-accent-text">Remind</Link></div>})}</div>:<div className="py-glass-soft p-4 text-[12px] text-text-3">Nothing scheduled today.</div>}</section>

  <section className="mt-6"><h2 className="m-0 mb-3 text-[20px] font-semibold tracking-[-.03em] text-text-1">Your routine</h2>{active.length?<div className="space-y-2.5">{active.map(item=><div key={item.id} className="py-glass-soft flex items-center gap-3 p-4"><div className="min-w-0 flex-1"><div className="text-[13.5px] font-semibold text-text-1">{item.name}</div><div className="mt-1 text-[10.5px] capitalize text-text-3">{item.dosage||"Dose not set"} · {scheduleLabel(item.frequency)}</div></div><form action={setSupplementActive.bind(null,item.id,false)}><button className="text-[10px] font-semibold text-text-3">Pause</button></form></div>)}</div>:null}</section>

  <form action={addSupplement} className="py-glass-soft mt-6 p-4"><div className="text-[13px] font-semibold text-text-1">Add to routine</div><div className="mt-3 space-y-2.5"><input name="name" required className="py-input" placeholder="Creatine, Retatrutide, etc."/><input name="dosage" className="py-input" placeholder="Dose, e.g. 5 g or 1 injection"/><div className="grid grid-cols-2 gap-2.5"><select name="timing" defaultValue="morning" className="py-input text-[12px]"><option value="morning">Morning</option><option value="with_food">With food</option><option value="pre_workout">Pre-workout</option><option value="post_workout">Post-workout</option><option value="evening">Evening</option></select><select name="frequency" defaultValue="daily" className="py-input text-[12px]"><option value="daily">Every day</option><option value="weekly">Once weekly</option><option value="weekdays">Weekdays</option><option value="training_days">Training days</option><option value="as_needed">As needed</option></select></div><select name="weeklyDay" defaultValue="1" className="py-input text-[12px]"><option value="1">Weekly day: Monday</option><option value="2">Weekly day: Tuesday</option><option value="3">Weekly day: Wednesday</option><option value="4">Weekly day: Thursday</option><option value="5">Weekly day: Friday</option><option value="6">Weekly day: Saturday</option><option value="0">Weekly day: Sunday</option></select><input name="notes" className="py-input" placeholder="Optional note"/></div><button className="py-liquid-button mt-3 w-full">Add supplement</button><p className="m-0 mt-2 text-center text-[9.5px] leading-relaxed text-text-3">Track only routines you already follow. Project You+ does not prescribe supplements or medication.</p></form>
 </main>
}
function isDue(frequency:string,day:number){if(frequency==="daily")return true;if(frequency==="weekdays")return day>=1&&day<=5;if(frequency==="training_days")return true;if(frequency.startsWith("weekly_"))return frequency===`weekly_${DAYS[day].toLowerCase()}`;if(frequency==="weekly")return day===1;return false}
function scheduleLabel(frequency:string){if(frequency.startsWith("weekly_"))return `every ${frequency.replace("weekly_","")}`;return frequency.replaceAll("_"," ")}
