"use client";
import { useState } from "react";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { signOut } from "@/lib/actions/auth";
const INITIAL_PERMISSIONS={Calendar:true,Fitness:true,Finances:true,Health:true,Location:false};
const INITIAL_NOTIFICATIONS={"Workout reminders":true,"Budget alerts":true,"Habit nudges":true,"Weekly review ready":true};
export default function SettingsPage(){const [permissions,setPermissions]=useState(INITIAL_PERMISSIONS);const [notifications,setNotifications]=useState(INITIAL_NOTIFICATIONS);return <main className="py-shell-narrow"><header className="mb-7"><div className="py-eyebrow mb-2">Control center</div><h1 className="py-title">Settings</h1><p className="py-subtitle">Control appearance, AI access, notifications and account preferences.</p></header><div className="space-y-5"><Section eyebrow="Appearance" title="Look & feel"><Row label="Theme" sub="Dark mode is the Project You+ default."><ThemeToggle/></Row></Section><Section eyebrow="AI Access" title="What your coach can use"><p className="mb-3 mt-0 text-[12.5px] leading-relaxed text-text-3">Turn a category off and the AI Coach will stop using that data in recommendations.</p>{Object.entries(permissions).map(([k,v])=><ToggleRow key={k} label={k} checked={v} onChange={(x)=>setPermissions(p=>({...p,[k]:x}))}/>)}</Section><Section eyebrow="Notifications" title="What should interrupt you"><div>{Object.entries(notifications).map(([k,v])=><ToggleRow key={k} label={k} checked={v} onChange={(x)=>setNotifications(n=>({...n,[k]:x}))}/>)}</div></Section><Section eyebrow="Account" title="Project You+ account"><form action={signOut}><button className="text-[13.5px] font-semibold text-danger">Sign out</button></form></Section></div></main>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="py-card p-5 sm:p-6"><div className="py-section-label text-accent-text">{eyebrow}</div><h2 className="py-section-title mb-4">{title}</h2>{children}</section>}
function Row({label,sub,children}:{label:string;sub:string;children:React.ReactNode}){return <div className="flex items-center justify-between gap-4"><div><div className="text-[14px] font-medium text-text-1">{label}</div><div className="mt-1 text-[12px] text-text-3">{sub}</div></div>{children}</div>}
function ToggleRow({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between border-b border-border py-3 last:border-b-0"><span className="text-[13.5px] text-text-1">{label}</span><button onClick={()=>onChange(!checked)} className="relative h-6 w-[42px] rounded-full transition-colors" style={{background:checked?"var(--accent)":"var(--border)"}}><span className="absolute top-[3px] h-[18px] w-[18px] rounded-full bg-white transition-transform" style={{transform:checked?"translateX(21px)":"translateX(3px)"}}/></button></div>}
