import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function MoneyPage(){
  const supabase=await createClient();
  const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);
  const[{data:accounts},{data:transactions},{data:holdings},{data:integrations}]=await Promise.all([
    supabase.from("finance_accounts").select("id,name,account_type,balance,institution,connected_via,last_synced_at").order("created_at"),
    supabase.from("transactions").select("amount,category,merchant,occurred_at,pending").gte("occurred_at",monthStart.toISOString()).order("occurred_at",{ascending:false}).limit(100),
    supabase.from("investment_holdings").select("id,ticker,name,quantity,price,value,provider,as_of").order("value",{ascending:false}).limit(20),
    supabase.from("integrations").select("provider,status,metadata"),
  ]);
  const rows=accounts??[],tx=transactions??[],portfolio=holdings??[];
  const plaidConnected=(integrations??[]).some((row)=>row.provider==="plaid"&&row.status==="connected");
  const assets=rows.filter((a)=>a.account_type!=="credit").reduce((sum,a)=>sum+Number(a.balance??0),0);
  const debt=rows.filter((a)=>a.account_type==="credit").reduce((sum,a)=>sum+Math.abs(Number(a.balance??0)),0);
  const netWorth=assets-debt;
  const income=tx.filter((t)=>Number(t.amount)>0).reduce((sum,t)=>sum+Number(t.amount),0);
  const spent=Math.abs(tx.filter((t)=>Number(t.amount)<0).reduce((sum,t)=>sum+Number(t.amount),0));
  const investmentValue=portfolio.reduce((sum,row)=>sum+Number(row.value??0),0);
  const hasData=rows.length>0;
  return <main className="py-mobile-shell md:py-shell-narrow">
    <header className="mb-6 flex items-start justify-between gap-4"><div><div className="text-[11px] text-text-3">Financial operating picture</div><h1 className="py-title mt-1">Finance</h1><p className="py-subtitle">Balances, cash flow, and investments become context for smarter weekly decisions.</p></div><Link href="/money/connect" className="py-glass rounded-full px-3.5 py-2.5 text-[11px] font-semibold text-accent-text">{plaidConnected?"Manage":"Connect"}</Link></header>

    <section className="py-trajectory-card p-5"><div className="flex items-center justify-between gap-3"><span className="text-[10px] font-semibold uppercase tracking-[.13em] text-white/55">Net position</span><span className={`py-glass-pill ${plaidConnected?"text-positive":"text-white/55"}`}>{plaidConnected?"Plaid connected":"Manual context"}</span></div><div className="mt-3 text-[39px] font-bold tracking-[-.06em] text-white">{hasData?money(netWorth):"—"}</div><p className="m-0 mt-1.5 text-[11px] text-white/48">{hasData?`${rows.length} account${rows.length===1?"":"s"} · ${money(assets)} assets · ${money(debt)} debt`:"Connect or add an account to build your financial baseline."}</p>{!hasData&&<Link href="/money/connect" className="py-liquid-button mt-5 w-full">Build financial context</Link>}</section>

    {hasData&&<section className="mt-3 grid grid-cols-3 gap-2.5"><Stat label="Income" value={money(income)} sub="this month"/><Stat label="Spent" value={money(spent)} sub="this month"/><Stat label="Invested" value={money(investmentValue||rows.filter((a)=>a.account_type==="investment").reduce((s,a)=>s+Number(a.balance??0),0))} sub="tracked"/></section>}

    <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><div className="text-[11px] text-text-3">Accounts</div><h2 className="m-0 mt-1 text-[21px] font-semibold tracking-[-.03em] text-text-1">Where your money lives</h2></div><Link href="/money/connect" className="text-[11px] font-semibold text-accent-text">Add or connect</Link></div>{rows.length?<div className="py-glass-soft divide-y divide-white/[.055] px-4">{rows.map((account)=><div key={account.id} className="flex items-center gap-3 py-3.5"><span className={`flex h-9 w-9 items-center justify-center rounded-full text-[11px] font-bold ${account.connected_via==="plaid"?"bg-accent-soft text-accent-text":"bg-white/[.035] text-text-2"}`}>{account.account_type==="investment"?"↗":account.account_type==="credit"?"C":"$"}</span><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-semibold text-text-1">{account.name}</span><span className="mt-0.5 block truncate text-[10px] capitalize text-text-3">{account.institution?`${account.institution} · `:""}{account.account_type??"account"} · {account.connected_via??"manual"}</span></span><span className={`text-[12px] font-semibold ${account.account_type==="credit"?"text-warn":"text-text-1"}`}>{account.account_type==="credit"?`−${money(Math.abs(Number(account.balance??0)))}`:money(Number(account.balance??0))}</span></div>)}</div>:<div className="py-glass-soft p-4 text-[12px] text-text-3">No financial accounts connected yet.</div>}</section>

    {portfolio.length>0&&<section className="mt-7"><div className="mb-3"><div className="text-[11px] text-text-3">Investments</div><h2 className="m-0 mt-1 text-[21px] font-semibold tracking-[-.03em] text-text-1">Current holdings</h2></div><div className="py-glass-soft divide-y divide-white/[.055] px-4">{portfolio.slice(0,8).map((holding)=><div key={holding.id} className="flex items-center gap-3 py-3.5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-positive-soft text-[10px] font-bold text-positive">{holding.ticker?.slice(0,4)||"INV"}</span><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-semibold text-text-1">{holding.name}</span><span className="mt-0.5 block text-[10px] text-text-3">{Number(holding.quantity||0).toLocaleString(undefined,{maximumFractionDigits:3})} shares · {holding.provider}</span></span><span className="text-[12px] font-semibold text-text-1">{money(Number(holding.value??0))}</span></div>)}</div><p className="m-0 mt-2 px-1 text-[9.5px] leading-relaxed text-text-3">Values reflect the most recent provider data available to Project You+. This view does not estimate future returns.</p></section>}

    {tx.length>0&&<section className="mt-7"><div className="mb-3"><div className="text-[11px] text-text-3">Activity</div><h2 className="m-0 mt-1 text-[21px] font-semibold tracking-[-.03em] text-text-1">Recent money movement</h2></div><div className="py-glass-soft divide-y divide-white/[.055] px-4">{tx.slice(0,8).map((item,index)=><div key={`${item.occurred_at}-${index}`} className="flex items-center gap-3 py-3"><span className="min-w-0 flex-1"><span className="block truncate text-[12.5px] font-semibold text-text-1">{item.merchant||item.category||"Transaction"}</span><span className="mt-0.5 block text-[9.5px] text-text-3">{new Date(item.occurred_at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}{item.pending?" · pending":""}</span></span><span className={`text-[11.5px] font-semibold ${Number(item.amount)>=0?"text-positive":"text-text-2"}`}>{Number(item.amount)>=0?"+":"−"}{money(Math.abs(Number(item.amount)))}</span></div>)}</div></section>}

    <Link href="/coach" className="py-glass-soft py-pressable mt-7 flex items-center gap-3 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-[14px] bg-accent-soft text-[10px] font-bold text-accent-text">AI</span><span className="min-w-0 flex-1"><span className="block text-[13.5px] font-semibold text-text-1">Ask about your money</span><span className="mt-0.5 block text-[10.5px] leading-relaxed text-text-3">Ask what you can save this week, where spending changed, or how a goal fits your current cash flow.</span></span><span className="text-[18px] text-text-3">›</span></Link>
  </main>
}
function money(value:number){return new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <div className="py-glass-soft p-3"><div className="text-[9px] text-text-3">{label}</div><div className="mt-2 truncate text-[16px] font-bold tracking-[-.035em] text-text-1">{value}</div><div className="mt-0.5 text-[8.5px] text-text-3">{sub}</div></div>}
