export type AchievementCategory = "score" | "consistency" | "health" | "finance" | "goals" | "planning" | "review" | "progression" | "special";
export type AchievementTier = "standard" | "major" | "elite";
export type AchievementDefinition = { key: string; title: string; description: string; category: AchievementCategory; tier: AchievementTier };
export type AchievementFacts = { activeDays: string[]; goalCompletions: string[]; workoutDays: string[]; reviewDates: string[]; onTargetBudgetMonths: string[]; profileCreatedAt: string | null; now?: Date };
export type QualifiedAchievement = AchievementDefinition & { earnedAt: string; evidence: Record<string, unknown> };
export const ACHIEVEMENTS: readonly AchievementDefinition[] = [
  { key: "first_day_completed", title: "First Day Completed", description: "Completed meaningful activity on the first tracked day.", category: "consistency", tier: "standard" },
  { key: "first_full_week", title: "First Full Week", description: "Recorded meaningful activity across a complete Monday–Sunday week.", category: "consistency", tier: "major" },
  { key: "seven_day_consistency", title: "7-Day Consistency", description: "Stayed active for seven consecutive days.", category: "consistency", tier: "major" },
  { key: "first_goal_completed", title: "First Goal Completed", description: "Completed the first tracked goal.", category: "goals", tier: "major" },
  { key: "three_workout_week", title: "3/3 Workout Week", description: "Completed three workouts in one Monday–Sunday week.", category: "health", tier: "major" },
  { key: "first_month", title: "First Month", description: "Built 30 days of history in Project You+.", category: "progression", tier: "standard" },
  { key: "first_weekly_review", title: "First Weekly Review", description: "Completed the first evidence-based Weekly Review.", category: "review", tier: "standard" },
  { key: "budget_month_completed", title: "Budget Month Completed", description: "Closed a tracked month on or under budget.", category: "finance", tier: "major" },
  { key: "thirty_day_discipline", title: "30-Day Discipline", description: "Recorded meaningful activity on 30 days within a 35-day period.", category: "consistency", tier: "elite" },
] as const;
export function qualifyAchievements(facts: AchievementFacts): QualifiedAchievement[] {
  const active = [...new Set(facts.activeDays)].sort(), workouts = [...new Set(facts.workoutDays)].sort(), result: QualifiedAchievement[] = [];
  add("first_day_completed", active[0], { day: active[0] }); const fullWeek = firstFullWeek(active); add("first_full_week", fullWeek, { weekEnding: fullWeek }); const run = firstRun(active, 7); add("seven_day_consistency", run, { endingOn: run }); add("first_goal_completed", [...facts.goalCompletions].sort()[0], {}); const workoutWeek = firstWeekWithAtLeast(workouts, 3); add("three_workout_week", workoutWeek, { weekEnding: workoutWeek });
  if (facts.profileCreatedAt) { const start = new Date(facts.profileCreatedAt), earned = new Date(start); earned.setUTCDate(earned.getUTCDate() + 30); if (earned <= (facts.now ?? new Date())) add("first_month", earned.toISOString(), { joinedAt: facts.profileCreatedAt }); }
  add("first_weekly_review", [...facts.reviewDates].sort()[0], {}); const budgetMonth = [...facts.onTargetBudgetMonths].sort()[0]; if (budgetMonth) add("budget_month_completed", `${budgetMonth}-28T12:00:00.000Z`, { month: budgetMonth }); const discipline = firstThirtyOfThirtyFive(active); add("thirty_day_discipline", discipline, { endingOn: discipline }); return result;
  function add(key: string, earnedAt: string | undefined, evidence: Record<string, unknown>) { if (!earnedAt) return; const definition = ACHIEVEMENTS.find((item) => item.key === key)!; result.push({ ...definition, earnedAt: earnedAt.length === 10 ? `${earnedAt}T12:00:00.000Z` : earnedAt, evidence }); }
}
function firstRun(days: string[], size: number) { const set = new Set(days); for (const start of days) { const date = new Date(`${start}T12:00:00Z`); let ok = true; for (let i = 1; i < size; i++) { const next = new Date(date); next.setUTCDate(date.getUTCDate() + i); if (!set.has(next.toISOString().slice(0, 10))) { ok = false; break; } } if (ok) { const end = new Date(date); end.setUTCDate(date.getUTCDate() + size - 1); return end.toISOString().slice(0, 10); } } }
function firstFullWeek(days: string[]) { const weeks = new Map<string, Set<number>>(); for (const day of days) { const date = new Date(`${day}T12:00:00Z`), monday = new Date(date); monday.setUTCDate(date.getUTCDate() - ((date.getUTCDay() + 6) % 7)); const key = monday.toISOString().slice(0, 10); if (!weeks.has(key)) weeks.set(key, new Set()); weeks.get(key)!.add(date.getUTCDay()); } for (const [monday, weekdays] of weeks) if (weekdays.size === 7) { const end = new Date(`${monday}T12:00:00Z`); end.setUTCDate(end.getUTCDate() + 6); return end.toISOString().slice(0, 10); } }
function firstWeekWithAtLeast(days: string[], count: number) { const weeks = new Map<string, string[]>(); for (const day of days) { const date = new Date(`${day}T12:00:00Z`), monday = new Date(date); monday.setUTCDate(date.getUTCDate() - ((date.getUTCDay() + 6) % 7)); const key = monday.toISOString().slice(0, 10); weeks.set(key, [...(weeks.get(key) ?? []), day]); } for (const values of weeks.values()) if (new Set(values).size >= count) return values.sort()[count - 1]; }
function firstThirtyOfThirtyFive(days: string[]) { for (let index = 29; index < days.length; index++) { const end = new Date(`${days[index]}T12:00:00Z`).getTime(), window = days.filter((day) => new Date(`${day}T12:00:00Z`).getTime() >= end - 34 * 86_400_000 && day <= days[index]); if (new Set(window).size >= 30) return days[index]; } }
