import "server-only";
import {createHash}from"node:crypto";
import type{UserContext}from"@/lib/ai/context";
import{createAdminClient}from"@/lib/supabase/admin";
import{createClient}from"@/lib/supabase/server";
import type{ProgressionState}from"@/lib/types/progression";
import type{CalibrationSummary,PatternObservation,RetentionIntelligence}from"@/lib/types/intelligence-summary";
import{loadLongitudinalContext}from"@/lib/ai/longitudinal-context";

const WEIGHTS:Record<string,number>={sleep:.15,fitness:.15,money:.15,productivity:.2,goals:.15,habits:.15,learning:.05};
export async function buildRetentionIntelligence(context:UserContext,progression:ProgressionState):Promise<RetentionIntelligence>{
 const client=await createClient();const{data:{user}}=await client.auth.getUser();if(!user)throw new Error("Not signed in.");const admin=createAdminClient(),now=new Date(),today=day(now),weekStart=new Date(now);weekStart.setDate(now.getDate()-6);weekStart.setHours(0,0,0,0);
 const[scoresRes,longitudinal]=await Promise.all([admin.from("score_snapshots").select("id,score,coverage_pct,captured_on").eq("user_id",user.id).order("captured_on",{ascending:false}).limit(30),loadLongitudinalContext(user.id,{days:60,limit:300})]);
 const scores=scoresRes.data??[],events=longitudinal.events,recentEvents=events.filter(event=>new Date(event.occurred_at)>=weekStart),eventCounts=countBy(recentEvents.map(event=>event.event_type)),activeDays=new Set(recentEvents.filter(event=>event.event_type.endsWith(".completed")||event.event_type==="meal.logged").map(event=>String(event.occurred_at).slice(0,10))).size;
 const missingDomains=Object.entries(context.domains).filter(([,value])=>value.availability==="unavailable").map(([name])=>name).filter(name=>["goals","tasks","habits","calendar","workout","nutrition","supplements","health","finance"].includes(name));
 const calibration:CalibrationSummary={coveragePct:context.score.coveragePct,scoreDays:progression.calibrationDays,status:context.score.coveragePct>=75&&progression.calibrationDays>=14?"established":"calibrating",missingDomains,message:context.score.coveragePct>=75&&progression.calibrationDays>=14?"Your score has enough breadth and history for stronger trend confidence.":`Your score is ${context.score.coveragePct}% covered across ${progression.calibrationDays} saved day${progression.calibrationDays===1?"":"s"}.`};
 const dueTasks=context.tasks.filter(task=>task.dueAt?.slice(0,10)===today),dailyHabits=context.habits.filter(habit=>habit.targetFrequency==="daily"),plannedWorkout=context.training.todaySession?1:0,dueSupplements=context.supplements.active.filter(item=>supplementDue(item.frequency,now.getDay()));
 const taskDone=dueTasks.filter(task=>task.completedAt).length,habitDone=new Set(events.filter(event=>event.event_type==="habit.completed"&&String(event.occurred_at).slice(0,10)===today).map(event=>event.source_id)).size,workoutDone=context.health.workoutStatus==="completed"?1:0,suppDone=context.supplements.loggedToday.filter(name=>dueSupplements.some(item=>item.name===name)).length;
 const planned=dueTasks.length+dailyHabits.length+plannedWorkout+dueSupplements.length,completed=Math.min(planned,taskDone+habitDone+workoutDone+suppDone),completionPct=planned?Math.round(completed/planned*100):null;
 const priorities=context.tasks.filter(task=>!task.completedAt).sort((a,b)=>rank(a.tier)-rank(b.tier)).slice(0,3).map(task=>task.title),patterns=discoverPatterns(events,scores);
 await persistPatterns(admin,user.id,patterns,now);const notices=await persistAchievementNotices(admin,user.id,progression,now);
 const points=[...scores].reverse().map(row=>({date:String(row.captured_on),score:Number(row.score)})),first=points[0]?.score,last=points.at(-1)?.score,change=first!=null&&last!=null&&points.length>1?last-first:null,average=points.length?Math.round(points.reduce((sum,item)=>sum+item.score,0)/points.length):null;
 const opportunity=context.score.opportunity,totalWeight=Math.max(.01,context.score.coveragePct/100),impact=opportunity?Math.max(1,Math.round((WEIGHTS[opportunity.key]??.1)/totalWeight*10)):0;
 return{generatedAt:now.toISOString(),daily:{headline:priorities.length||context.schedule.length?"Your day is ready.":"Your day needs one real priority.",priorities,fixedCommitments:context.schedule.filter(event=>event.startAt.slice(0,10)===today).map(event=>({id:event.id,title:event.title,startAt:event.startAt,endAt:event.endAt})),coverage:calibration},evening:{headline:completionPct==null?"Today has no measurable plan yet.":`You closed ${completionPct}% of today.`,completionPct,completed,planned,explanation:planned?`${completed} of ${planned} connected commitments are complete.`:"Add scheduled tasks or routines to measure daily completion."},weeklyReviewInput:{window:{from:weekStart.toISOString(),to:now.toISOString()},eventCounts,score:points.length?{current:context.score.score.score,change,high:Math.max(...points.map(item=>item.score)),low:Math.min(...points.map(item=>item.score))}:null,activeDays,patterns},scoreExplanation:{score:context.score.score.score,change,strongest:context.score.strongest?.key??null,opportunity:opportunity?.key??null,rationale:context.score.rationale,coverage:calibration},historicalTrend:{direction:change==null?"unavailable":change>1?"up":change< -1?"down":"flat",change,average,points},projectedScoreImpact:opportunity?{domain:opportunity.key,estimatedPoints:{low:Math.max(1,Math.floor(impact/2)),high:impact},basis:`Estimate if ${opportunity.key} improves by roughly 5–10 domain points while other measured domains stay stable.`}:null,achievementNotices:notices};
}

function discoverPatterns(events:Array<{id:string;event_type:string;occurred_at:string}>,scores:Array<{score:number;captured_on:string}>):PatternObservation[]{const rows:PatternObservation[]=[];const misses=events.filter(event=>event.event_type.endsWith(".missed"));const groups=new Map<string,typeof misses>();for(const event of misses){const key=`${event.event_type}:${new Date(event.occurred_at).getDay()}`;groups.set(key,[...(groups.get(key)??[]),event])}for(const[key,items]of groups)if(items.length>=2){const[type,weekday]=key.split(":");rows.push({key:`repeated-miss:${key}`,observation:`${items.length} ${type.replace(".missed","")} misses occurred on ${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][Number(weekday)]}.`,whyItMatters:"Repeated timing is more actionable than an isolated miss.",evidenceIds:items.slice(-6).map(item=>item.id),confidence:items.length>=3?"high":"medium"})}if(scores.length>=3){const newest=Number(scores[0].score),oldest=Number(scores.at(-1)?.score);if(Math.abs(newest-oldest)>=5)rows.push({key:`score-direction:${newest>oldest?"up":"down"}`,observation:`Your saved score moved ${newest>oldest?"up":"down"} ${Math.abs(newest-oldest)} points across the available history.`,whyItMatters:"A multi-day move is more meaningful than a single score.",evidenceIds:[],confidence:scores.length>=7?"high":"medium"})}return rows.slice(0,5)}
async function persistPatterns(admin:ReturnType<typeof createAdminClient>,userId:string,patterns:PatternObservation[],now:Date){const week=day(daysAgo(now,(now.getDay()+6)%7));await Promise.all(patterns.map(item=>admin.from("behavior_events").upsert({user_id:userId,event_type:"pattern.discovered",occurred_at:now.toISOString(),source_table:null,source_id:null,payload:item,dedupe_key:`pattern:${week}:${hash(item.key)}`},{onConflict:"user_id,dedupe_key",ignoreDuplicates:true})))}
async function persistAchievementNotices(admin:ReturnType<typeof createAdminClient>,userId:string,progression:ProgressionState,now:Date){const recent=progression.achievements.filter(item=>now.getTime()-new Date(item.unlockedAt).getTime()<=7*86400000).slice(0,3);await Promise.all(recent.map(item=>admin.from("notifications").upsert({user_id:userId,title:item.title==="1%"?"You reached the 1% level.":`${item.title} unlocked.`,body:item.category==="score"||item.category==="milestone"?"Your score progression reached a new recognition point.":"Your consistent actions created a new achievement.",notification_key:`achievement:${item.id}`,notification_type:item.category==="score"||item.category==="milestone"||item.category==="elite"?"milestone":"achievement",metadata:{achievement_id:item.id,achievement_key:item.key}},{onConflict:"user_id,notification_key",ignoreDuplicates:true})));return recent.map(item=>({achievementId:item.id,title:item.title,unlockedAt:item.unlockedAt,kind:(item.category==="score"||item.category==="milestone"||item.category==="elite"?"milestone":"achievement")as"achievement"|"milestone"}))}
function supplementDue(frequency:string,weekday:number){if(frequency==="daily")return true;if(frequency==="weekdays")return weekday>=1&&weekday<=5;if(frequency.startsWith("weekly_"))return frequency===`weekly_${["sunday","monday","tuesday","wednesday","thursday","friday","saturday"][weekday]}`;return frequency==="weekly"&&weekday===1}
function countBy(values:string[]){return values.reduce<Record<string,number>>((out,value)=>{out[value]=(out[value]??0)+1;return out},{})}function rank(tier:string){return tier==="critical"?0:tier==="important"?1:2}function hash(value:string){return createHash("sha256").update(value).digest("hex").slice(0,24)}function daysAgo(date:Date,count:number){const copy=new Date(date);copy.setDate(copy.getDate()-count);return copy}function day(date:Date){return date.toISOString().slice(0,10)}
