import Link from "next/link";
import { getProfile } from "@/lib/data/profile";
import { getGoals } from "@/lib/data/goals";
import { getTasks } from "@/lib/data/tasks";
import { getHabits } from "@/lib/data/habits";
import { getHealthOverview } from "@/lib/data/health";
import { createClient } from "@/lib/supabase/server";
import { SystemActionCard } from "@/components/today/system-action-card";
import { SystemHabitCard } from "@/components/today/system-habit-card";
import type { Goal, Habit, Profile, Task } from "@/lib/types";

const tierWeight:Record<Task["tier"],number>={critical:30,important:20,optional:10};
function taskScore(task:Task,activeGoalIds:Set<string>){let score=tierWeight[task.tier];if(task.goalId&&activeGoalIds.has(task.goalId))score+=100;if(task.dueAt){const hours=(new Date(task.dueAt).getTime()-Date.now())/36e5;if(hours<=0)score+=45;else if(hours<=24)score+=30;else if(hours<=72)score+=15;}return score;}
function dueLabel(dueAt:string|null,timezone:string){if(!dueAt)return"Flexible";const date=new Date(dueAt),today=userDate(new Date(),timezone),due=userDate(date,timezone);if(due<=today)return"Due today";const tomorrow=userDate(new Date(Date.now()+86400000),timezone);if(due===tomorrow)return"Due tomorrow";return date.toLocaleDateString(undefined,{month:"short",day:"numeric"});}

export default async function TodayPage(){
  const [profile,goals,tasks,habits,signals,health]=await Promise.all([getProfile(),getGoals(),getTasks(),getHabits(),getSetupSignals(),getHealthOverview()]);
  const timezone=profile.timezone||"UTC",today=userDate(new Date(),timezone),todayDay=weekday(today),firstName=(profile.fullName??"there").split(" ")[0];
  const activeGoals=goals.filter(goal=>goal.status==="active"),activeGoalIds=new Set(activeGoals.map(goal=>goal.id)),goalById=new Map(activeGoals.map(goal=>[goal.id,goal]));
  const openTasks=tasks.filter(task=>!task.completedAt).sort((a,b)=>taskScore(b,activeGoalIds)-taskScore(a,activeGoalIds));
  const dueSystemTasks=openTasks.filter(task=>todayEligible(task,today,timezone));const legacyTasks=openTasks.filter(task=>!task.actionKind);const topMoves=dedupeTasks([...dueSystemTasks,...legacyTasks]).slice(0,3),bestTask=topMoves[0];
  const prioritizedHabits=[...habits].filter(habit=>habitDueToday(habit,todayDay)).sort((a,b)=>Number(Boolean(b.goalId))-Number(Boolean(a.goalId))||a.consistencyPct-b.consistencyPct).slice(0,3);
  const review=profile.blueprint?.activeSystem?.contextDefinitions?.weeklyReview??null;const coachMessage=activeSystemCoachMessage(profile,bestTask,health.training.todayWorkout?.title??null,prioritizedHabits.length);

  const setupItems=[
    {label:"Define a meaningful goal",href:"/goals/new",done:activeGoals.length>0},{label:"Add a next action",href:"/tasks/new",done:tasks.length>0},{label:"Create a supporting habit",href:"/habits",done:habits.length>0},{label:"Add health context",href:"/health",done:signals.health},{label:"Build your money picture",href:"/money",done:signals.money},{label:"Put something on your calendar",href:"/calendar",done:signals.calendar},
  ];
  const setupDone=setupItems.filter(item=>item.done).length,setupPercent=Math.round(setupDone/setupItems.length*100);

  return <main className="py-mobile-shell md:py-shell-narrow">
    <header className="py-animate-in mb-7 flex items-center justify-between gap-4"><div><div className="text-[13px] font-medium text-text-2">{greeting()}</div><h1 className="m-0 mt-0.5 text-[32px] font-bold tracking-[-0.045em] text-text-1">{firstName}</h1><div className="mt-1 text-[12px] text-text-3">{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</div></div><Link href="/profile" className="py-glass flex h-11 w-11 items-center justify-center rounded-full text-[12px] font-bold text-text-1">{firstName.slice(0,2).toUpperCase()}</Link></header>

    {!profile.onboardingCompleted&&setupPercent<100&&<section className="py-glass-soft py-animate-in py-stagger-1 mb-4 p-[18px]"><div className="flex items-start justify-between gap-4"><div><div className="py-eyebrow text-accent-text">Make Project You+ yours</div><h2 className="m-0 mt-1.5 text-[20px] font-semibold tracking-[-0.025em] text-text-1">Your setup is {setupPercent}% complete</h2><p className="m-0 mt-1.5 max-w-[340px] text-[12.5px] leading-relaxed text-text-2">The more real context you add, the better Project You+ can prioritize your day.</p></div><span className="py-glass-pill text-accent-text">{setupDone}/{setupItems.length}</span></div><div className="mt-4 py-progress-track"><div className="py-progress-fill" style={{width:`${setupPercent}%`}}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{setupItems.filter(item=>!item.done).slice(0,4).map(item=><Link key={item.label} href={item.href} className="py-pressable flex items-center gap-2 rounded-[14px] border border-white/5 bg-white/[.025] px-3 py-2.5 text-[12px] font-medium text-text-2"><span className="h-2 w-2 rounded-full border border-accent"/><span>{item.label}</span><span className="ml-auto text-text-3">›</span></Link>)}</div></section>}

    <section className="py-glass-hero py-animate-in py-stagger-2 p-5 sm:p-6">
      {profile.onboardingCompleted&&profile.blueprint?.activeSystem&&<div className="mb-5 border-b border-white/[.075] pb-5"><div className="flex items-center gap-2 text-[10.5px] font-semibold uppercase tracking-[.15em] text-[#C8AEFF]"><span className="py-pulse-dot h-2 w-2 rounded-full bg-accent-2"/>Project You+ Coach</div><p className="m-0 mt-3 text-[13px] leading-relaxed text-[#D4CEDD]">{coachMessage}</p></div>}
      <div className="flex items-center gap-2 text-[10.5px] font-semibold uppercase tracking-[.15em] text-[#C8AEFF]"><span className="h-2 w-2 rounded-full bg-accent-2"/>Next best action</div>
      {bestTask?<div className="mt-4"><SystemActionCard task={bestTask} goalTitle={bestTask.goalId?goalById.get(bestTask.goalId)?.title:undefined} hero/></div>:activeGoals[0]?<><h2 className="m-0 mt-4 text-[27px] font-bold tracking-[-0.04em] text-white">Give {activeGoals[0].title} a next move.</h2><p className="m-0 mt-2 text-[13px] leading-relaxed text-[#C2BED0]">Your goal is clear. Add one concrete action so Today can start prioritizing for you.</p><Link href="/tasks/new" className="py-liquid-button mt-5 w-full">Create next action</Link></>:<><h2 className="m-0 mt-4 text-[27px] font-bold tracking-[-0.04em] text-white">Give Project You+ something worth optimizing.</h2><p className="m-0 mt-2 text-[13px] leading-relaxed text-[#C2BED0]">Start with one real goal. We’ll turn it into actions, habits, and visible momentum.</p><Link href="/goals/new" className="py-liquid-button mt-5 w-full">Create your first goal</Link></>}
    </section>

    {health.training.todayWorkout&&<section className="py-glass-soft py-animate-in mt-4 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[14px] bg-accent/10 text-[10px] font-bold text-accent-text">FIT</span><div className="min-w-0 flex-1"><div className="py-eyebrow">Scheduled health action</div><div className="mt-1 text-[14px] font-semibold text-text-1">{health.training.todayWorkout.title}</div><div className="mt-1 text-[10.5px] text-text-3">{health.training.todayWorkout.focus} · {health.training.todayWorkout.duration} min · {health.training.status.replaceAll("_"," ")}</div></div><Link href="/health" className="min-h-10 rounded-xl border border-white/[.08] px-3 py-2 text-[10.5px] font-semibold text-accent-text">Open</Link></div></section>}

    <section className="py-animate-in py-stagger-3 mt-7"><div className="mb-3 flex items-end justify-between gap-3"><div><div className="py-eyebrow">Execution</div><h2 className="m-0 mt-1 text-[22px] font-semibold tracking-[-0.03em] text-text-1">Your 3 moves</h2></div><Link href="/tasks" className="text-[12px] font-semibold text-accent-text">All tasks</Link></div>{topMoves.length?<div className="py-glass-soft divide-y divide-white/[.06] px-4">{topMoves.map((task,index)=><SystemActionCard key={task.id} task={task} goalTitle={task.goalId?goalById.get(task.goalId)?.title:undefined} index={index}/>)}</div>:<EmptyRow href="/tasks/new" title="No actions due today" sub="Your active system has no additional action due right now." cta="Add action"/>}</section>

    <section className="py-animate-in py-stagger-4 mt-7"><div className="mb-3 flex items-end justify-between gap-3"><div><div className="py-eyebrow">Consistency</div><h2 className="m-0 mt-1 text-[22px] font-semibold tracking-[-0.03em] text-text-1">Habits due today</h2></div><Link href="/habits" className="text-[12px] font-semibold text-accent-text">Habits</Link></div>{prioritizedHabits.length?<div className="grid gap-2.5">{prioritizedHabits.map(habit=><SystemHabitCard key={habit.id} habit={habit} goalTitle={habit.goalId?goalById.get(habit.goalId)?.title:undefined}/>)}</div>:<EmptyRow href="/habits" title="No habits due today" sub="Your system is intentionally not filling every available day." cta="View habits"/>}</section>

    {review&&<section className="py-glass-soft py-animate-in mt-7 flex items-center gap-3 p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[14px] bg-white/[.035] text-[10px] font-bold text-text-2">WR</span><div className="min-w-0 flex-1"><div className="text-[13px] font-semibold text-text-1">Next Weekly Review</div><div className="mt-0.5 text-[11px] text-text-3">{dayName(review.day)} · {formatTime(review.time)} · review what worked before changing the system</div></div><Link href="/review" className="text-[11px] font-semibold text-accent-text">Review</Link></section>}

    <section className="py-animate-in py-stagger-5 mt-7"><div className="mb-3 flex items-end justify-between gap-3"><div><div className="py-eyebrow">Direction</div><h2 className="m-0 mt-1 text-[22px] font-semibold tracking-[-0.03em] text-text-1">Goal momentum</h2></div><Link href="/goals" className="text-[12px] font-semibold text-accent-text">Goals</Link></div>{activeGoals.length?<div className="py-glass-soft divide-y divide-white/[.06] px-4">{activeGoals.slice(0,3).map(goal=>{const goalTasks=openTasks.filter(task=>task.goalId===goal.id).length,goalHabits=habits.filter(habit=>habit.goalId===goal.id).length;return <Link key={goal.id} href={`/goals/${goal.id}`} className="py-pressable block py-4"><div className="flex items-center justify-between gap-4"><span className="truncate text-[14px] font-semibold text-text-1">{goal.title}</span><span className="text-[12px] font-bold text-accent-text">{goal.progress}%</span></div><div className="mt-2.5 py-progress-track"><div className="py-progress-fill" style={{width:`${goal.progress}%`}}/></div><div className="mt-2 text-[10.5px] text-text-3">{goalTasks} open action{goalTasks===1?"":"s"} · {goalHabits} supporting habit{goalHabits===1?"":"s"}</div></Link>;})}</div>:<EmptyRow href="/goals/new" title="No active goals yet" sub="Goals give your tasks and habits a reason to exist." cta="Add goal"/>}</section>

    <Link href="/coach" className="py-glass-soft py-pressable mt-7 flex items-center gap-3 p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[15px] bg-accent text-[11px] font-bold text-white">AI</span><span className="min-w-0 flex-1"><span className="block text-[13px] font-semibold text-text-1">Coach read</span><span className="mt-0.5 block text-[12px] leading-relaxed text-text-2">{coachRead(bestTask,activeGoals,habits)}</span></span><span className="text-[22px] text-text-3">›</span></Link>
  </main>;
}

async function getSetupSignals(){const supabase=await createClient();const [{count:health},{count:money},{count:calendar}]=await Promise.all([supabase.from("health_metrics").select("id",{count:"exact",head:true}),supabase.from("finance_accounts").select("id",{count:"exact",head:true}),supabase.from("calendar_events").select("id",{count:"exact",head:true})]);return{health:(health??0)>0,money:(money??0)>0,calendar:(calendar??0)>0};}
function greeting(){const hour=new Date().getHours();if(hour<12)return"Good morning";if(hour<18)return"Good afternoon";return"Good evening";}
function coachRead(bestTask:Task|undefined,goals:Goal[],habits:{goalId?:string|null}[]){if(!goals.length)return"Create one meaningful goal first. Everything else becomes easier to prioritize once the destination is clear.";if(!bestTask)return`Your clearest gap is execution. Add one next action for ${goals[0].title}.`;const linkedHabits=habits.filter(habit=>habit.goalId===bestTask.goalId).length;if(bestTask.goalId&&linkedHabits===0)return"Your top action is linked to a goal, but that goal has no supporting habit yet. Add one repeatable behavior to protect momentum.";return`Start with “${bestTask.title}.” It is currently the strongest combination of goal alignment, urgency, and priority.`;}
function activeSystemCoachMessage(profile:Profile,bestTask:Task|undefined,workout:string|null,dueHabits:number){const style=String((profile.blueprint?.onboarding?.coachingPreferences as any)?.style??"balanced");const parts=[bestTask?`start with ${bestTask.title}`:"start with your first available priority",workout?`follow your scheduled ${workout}`:null,dueHabits?`complete ${dueHabits===1?"the habit":"the habits"} due today`:null].filter(Boolean).join(", ");if(style==="direct")return`Your system is active. ${capitalize(parts)}. If the full version will not fit, use the minimum version and keep moving. We’ll adjust from evidence, not perfection.`;if(style==="gentle")return`Your system is active. Today is intentionally manageable: ${parts}. Use the minimum version when needed, and we’ll learn from what actually works.`;return`Your system is ready. Today is intentionally simple: ${parts}. We’ll build from evidence—not perfection.`;}
function todayEligible(task:Task,today:string,timezone:string){if(!task.actionKind)return true;const due=task.dueAt?userDate(new Date(task.dueAt),timezone):null;if(task.domain==="money")return Boolean(due&&due<=today);if(due&&due>today)return false;return true;}
function habitDueToday(habit:Habit,day:number){if(habit.preferredDays?.length)return habit.preferredDays.includes(day);return habit.targetFrequency==="daily";}
function userDate(date:Date,timezone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);return`${parts.find(p=>p.type==="year")?.value}-${parts.find(p=>p.type==="month")?.value}-${parts.find(p=>p.type==="day")?.value}`;}
function weekday(date:string){const d=new Date(`${date}T12:00:00Z`);return d.getUTCDay();}
function dedupeTasks(tasks:Task[]){return Array.from(new Map(tasks.map(task=>[task.id,task])).values());}
function formatTime(value:string){const [h,m]=value.slice(0,5).split(":").map(Number);return`${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`;}
function dayName(day:number){return["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][day]??"Weekly";}
function capitalize(value:string){return value?value[0].toUpperCase()+value.slice(1):value;}
function EmptyRow({href,title,sub,cta}:{href:string;title:string;sub:string;cta:string}){return <Link href={href} className="py-glass-soft py-pressable flex items-center gap-3 p-4"><span className="py-empty-icon">+</span><span className="min-w-0 flex-1"><span className="block text-[14px] font-semibold text-text-1">{title}</span><span className="mt-0.5 block text-[11.5px] leading-relaxed text-text-3">{sub}</span></span><span className="text-[11.5px] font-semibold text-accent-text">{cta}</span></Link>;}
