import { addWorkSchedule, deleteWorkSchedule, setWorkScheduleActive } from "@/lib/actions/work-schedule";
import { createClient } from "@/lib/supabase/server";

const DAYS = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

export default async function WorkSchedulePage(){
  const supabase=await createClient();
  const {data:rows}=await supabase.from("work_schedules").select("id,label,days_of_week,start_time,end_time,active").order("created_at");
  return <main className="py-mobile-shell md:py-shell-narrow">
    <header className="mb-7"><h1 className="py-title">Work schedule</h1><p className="py-subtitle">Protect recurring work hours so Dashboard and Coach understand when your time is actually available.</p></header>
    <form action={addWorkSchedule} className="py-glass-soft p-4"><h2 className="m-0 text-[18px] font-semibold text-text-1">Add recurring block</h2><div className="mt-4 space-y-3"><input name="label" className="py-input" defaultValue="Work" placeholder="Work, school, family…"/><div className="grid grid-cols-2 gap-2.5"><label className="text-[10px] text-text-3">Start<input type="time" name="startTime" required className="py-input mt-1 min-h-[44px] py-2 text-[12px]"/></label><label className="text-[10px] text-text-3">End<input type="time" name="endTime" required className="py-input mt-1 min-h-[44px] py-2 text-[12px]"/></label></div><div><div className="mb-2 text-[10px] text-text-3">Days</div><div className="grid grid-cols-7 gap-1.5">{DAYS.map((day,index)=><label key={day} className="relative"><input type="checkbox" name="days" value={index} className="peer sr-only"/><span className="flex h-9 items-center justify-center rounded-[11px] border border-white/[.07] bg-white/[.025] text-[9.5px] font-semibold text-text-3 transition peer-checked:border-accent/50 peer-checked:bg-accent-soft peer-checked:text-accent-text">{day[0]}</span></label>)}</div></div></div><button className="py-liquid-button mt-4 w-full">Add schedule</button></form>
    <section className="mt-7"><h2 className="m-0 mb-3 text-[20px] font-semibold tracking-[-.025em] text-text-1">Recurring time</h2>{(rows??[]).length?<div className="py-glass-soft divide-y divide-white/[.06] px-4">{(rows??[]).map((row)=><div key={row.id} className="flex items-center gap-3 py-4"><span className={`h-2.5 w-2.5 rounded-full ${row.active?"bg-positive":"bg-text-3"}`}/><div className="min-w-0 flex-1"><div className="text-[13.5px] font-semibold text-text-1">{row.label}</div><div className="mt-0.5 text-[10.5px] text-text-3">{(row.days_of_week??[]).map((day:number)=>DAYS[day]).join(" · ")} · {time(row.start_time)}–{time(row.end_time)}</div></div><form action={setWorkScheduleActive.bind(null,row.id,!row.active)}><button className="text-[10.5px] font-semibold text-text-2">{row.active?"Pause":"Resume"}</button></form><form action={deleteWorkSchedule.bind(null,row.id)}><button className="text-[10.5px] text-text-3">Delete</button></form></div>)}</div>:<div className="py-glass-soft p-4 text-[12px] leading-relaxed text-text-3">No recurring work schedule yet. Add only the blocks that consistently limit your available time.</div>}</section>
  </main>
}
function time(value:string){return new Date(`2000-01-01T${value}`).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
