import Image from "next/image";
import Link from "next/link";
import { PROGRESSION_CONFIG } from "@/lib/progression/config";
import { BetaForm } from "./beta-form";
import { WebsiteMotion } from "./motion";
import "./website.css";
const products = [
  { id: "trajectory", name: "Trajectory", title: <>Know where<br />you’re going.</>, line: "Your score is useful. Your direction is more important.", description: "See where you are, where your commitments can take you, and what changes the outcome.", conclusion: "Your calendar tells you what you planned. Your trajectory tells you what you actually did.", short: "Know where you’re heading.", steps: ["Where you are.", "Where you’re heading.", "What changes the outcome."] },
  { id: "today", name: "Today", title: <>Know what<br />matters today.</>, line: "A clear next move. A reason behind it.", description: "Your goals, schedule, habits, health and previous behavior become an actionable day. The actions most likely to move your life forward.", conclusion: "Less deciding what to do. More becoming who you want to be.", short: "Know what matters now.", steps: ["Start with your goals.", "Make room for real life.", "Close the loop."] },
  { id: "coach", name: "Project You+ Coach", title: <>One Coach.<br />Your whole life.</>, line: "Some days need a different plan.", description: "YOU+ learns your goals, patterns, commitments and progress so its guidance gets more useful over time. Understand a missed pattern. Adjust a difficult day. Find your highest-impact next move.", conclusion: "A difficult yesterday doesn’t have to become a difficult week.", short: "Know what to change.", steps: ["Understand the pattern.", "Find the adjustment.", "Move forward again."] },
  { id: "review", name: "Weekly Review", title: <>Your week.<br />Understood.</>, line: "Progress becomes visible.", description: "Every week, YOU+ shows what moved, what didn’t, what it learned and what should change next. Turn completed actions and consistent habits into a clearer next week.", conclusion: "Do. Learn. Adjust. Become.", short: "Know whether it worked.", steps: ["What moved.", "What you learned.", "What changes next."] },
];
function ProductImage({ id, priority = false }: { id: string; priority?: boolean }) {
  const product = products.find(item => item.id === id)!;
  return <Image src={`/website/${id}-v1.webp`} alt={`${product.name}: actual YOU+ application interface using the existing Michael demo persona; illustrative values, not member results.`} width={430} height={932} priority={priority} sizes="(max-width: 799px) 88vw, 430px" />;
}
function Device({ id, priority = false }: { id: string; priority?: boolean }) { return <div className="product-device"><ProductImage id={id} priority={priority} /></div>; }
export function PublicHomepage() {
  return <main className="youplus-site" id="top">
    <WebsiteMotion />
    <a className="site-skip" href="#product">Skip to product</a>
    <header className="site-header"><a href="#top" className="site-brand" aria-label="Project You+ home"><Image src="/project-you-plus-logo.svg" width={44} height={44} alt="Project You+" /><span>Project You<span className="brand-plus">+</span></span></a><nav aria-label="Main navigation"><a href="#product" className="desktop-nav">Product</a><a href="#vision" className="desktop-nav">Vision</a><a href="#beta-form" className="nav-beta" data-beta-cta="nav">Join beta <span aria-hidden="true">↗</span></a></nav></header>
    <section className="site-hero" aria-labelledby="hero-title">
      <div className="hero-copy"><p className="site-eyebrow hero-enter">YOUR AI LIFE OPERATING SYSTEM</p><h1 id="hero-title" className="hero-enter">Become who<br />you said you<br />would <span>become.</span></h1><p className="hero-description hero-enter">Project You+ connects your goals, schedule, health, habits and finances to show where you are, what matters today, and whether you’re actually moving forward.</p><div className="hero-actions hero-enter"><a className="site-button" href="#beta-form" data-beta-cta="hero">Join the private beta <span aria-hidden="true">↗</span></a><a className="text-link" href="#product">See how it works <span aria-hidden="true">↓</span></a></div><p className="hero-footnote hero-enter">One life. A clearer direction.</p></div>
      <div className="hero-product" aria-label="YOU+ Today product preview"><div className="hero-rule" /><Device id="today" priority /><p className="preview-note">Actual product. Demo persona. Illustrative values.</p></div>
    </section>
    <section className="connected-section" id="vision" data-scene>
      <div className="section-wrap"><p className="site-eyebrow" data-reveal>THE WHOLE YOU</p><h2 data-reveal>Your life isn’t<br />one dashboard.</h2><p className="section-intro" data-reveal>Separate tools see separate pieces.<br />Your life happens between them.</p><div className="life-areas" aria-label="Connected life areas">{["Goals", "Calendar", "Health", "Habits", "Finances", "Progress"].map((name, index) => <span key={name} style={{ "--area-index": index } as React.CSSProperties}>{name}<span aria-hidden="true">+</span></span>)}</div><div className="connected-finish" data-reveal><Image src="/project-you-plus-logo.svg" width={88} height={88} alt="Project You+" /><h2>YOU+ connects them.</h2><p>One system that understands what you’re trying to become — and whether your actions are actually taking you there.</p></div></div>
    </section>
    <section id="product" className="product-story" aria-label="How YOU+ works">
      <div className="story-device-column" aria-hidden="true"><div className="story-device-sticky"><div className="product-device layered-device">{products.map((product, index) => <div className="device-layer" key={product.id} data-active={index === 0}><ProductImage id={product.id} /></div>)}</div><p className="preview-note">Actual product · illustrative demo data</p><div className="device-chapter-label">YOUR LIFE. COMING INTO FOCUS.</div></div></div>
      <div className="story-copy-column">{products.map((product, index) => <article id={product.id} key={product.id} className={`story-chapter chapter-${product.id}`} data-scene><div className="chapter-copy"><p className="site-eyebrow"><span className="chapter-index">0{index + 1}</span>{product.name}</p><h2>{product.title}</h2><h3>{product.line}</h3><p className="chapter-description">{product.description}</p><div className="chapter-steps">{product.steps.map((step, stepIndex) => <p key={step} style={{ "--step": stepIndex } as React.CSSProperties}><span aria-hidden="true">0{stepIndex + 1}</span>{step}</p>)}</div><p className="chapter-conclusion">{product.conclusion}</p></div><div className="mobile-product"><Device id={product.id} /><p className="preview-note">Actual product · illustrative demo data</p></div></article>)}</div>
    </section>
    <section className="learning-section" data-scene><div className="section-wrap"><p className="site-eyebrow" data-reveal>CONTEXT BECOMES CLARITY</p><h2><span className="learning-first">It doesn’t just<br />track you.</span><span className="learning-second">It learns you.</span></h2><div className="pattern-lines" aria-label="Patterns YOU+ can learn"><p>Your recurring weak days.</p><p>The habits that hold.</p><p>The commitments that collide.</p><p>The adjustments that work.</p></div><p className="learning-equation">More use <span>→</span> More context <span>→</span> Better guidance</p></div></section>
    <section className="progression-section" id="progression"><div className="progression-intro"><Image src="/website/one-percent.webp" width={105} height={105} alt="The approved 1% progression mark" className="one-percent-mark" /><p className="site-eyebrow" data-reveal>THE 1% SYSTEM</p><h2 data-reveal>Built for<br />progression.</h2><p data-reveal>1% isn’t a streak.<br />It’s sustained alignment.</p></div><div className="milestones">{PROGRESSION_CONFIG.milestones.map(milestone => <div className="milestone" key={milestone.level}><span className="milestone-number">{milestone.level}</span><div><span className="milestone-stage">{milestone.stage}</span><span className="milestone-caption">{milestone.level === 99 ? "Sustained. Across your life." : "Build the person behind the score."}</span></div></div>)}</div><p className="progression-note">Built across weeks and months. Never one perfect day.</p></section>
    <section className="highlights-section" aria-labelledby="highlights-title"><div className="highlights-heading"><div><p className="site-eyebrow">THE DAILY LOOP</p><h2 id="highlights-title">Clarity. In four moves.</h2></div><p>Explore the product <span aria-hidden="true">→</span></p></div><div className="highlight-track" tabIndex={0} role="region" aria-label="Swipe or scroll to explore four product highlights">{products.map((product, index) => <a className="highlight" key={product.id} href={`#${product.id}`}><div className="highlight-image"><ProductImage id={product.id} /></div><div className="highlight-caption"><span>0{index + 1}</span><div><h3>{product.id === "coach" ? "Coach" : product.name}</h3><p>{product.short}</p></div><span aria-hidden="true">↗</span></div></a>)}</div><p className="highlight-note">Real application captures with the existing demo persona. Values illustrate the interface and are not member results.</p></section>
    <section className="beta-section" id="beta" aria-labelledby="beta-title"><div className="beta-intro"><Image src="/project-you-plus-logo.svg" width={86} height={86} alt="Project You+" /><p className="site-eyebrow">PRIVATE BETA</p><h2 id="beta-title">Be one of the first<br />to become <span>YOU+.</span></h2><p>Help shape the AI life operating system built around your goals, health, schedule, habits and finances.</p></div><div id="beta-form"><BetaForm /></div></section>
    <footer className="site-footer"><div className="footer-top"><a href="#top" className="site-brand"><Image src="/project-you-plus-logo.svg" width={44} height={44} alt="Project You+" /><span>Become who you said you would become.</span></a><div><a href="#privacy">Privacy</a><Link href="/login" prefetch={false}>Member sign in <span aria-hidden="true">↗</span></Link></div></div><details id="privacy"><summary>Beta signup & privacy</summary><p>We collect your name and email to manage private beta access. Your improvement goal and pricing response are optional and help guide product research. Please don’t include sensitive health or financial details. Submissions are stored in our Supabase database and processed through Vercel.</p><p>We also record visits, beta button clicks, form starts and successful signups with an anonymous visit identifier and available campaign information. We retain only the referring website’s hostname. This page sends no automatic email and collects no payment details.</p></details><div className="footer-bottom"><span>© {new Date().getFullYear()} Project You+</span><span>Your AI Life Operating System.</span><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
