"use client";

import Link from "next/link";
import { CoachComposer } from "./coach-composer";
import { CoachMessageContent } from "./coach-message";
import { useRouter } from "next/navigation";
import { useRef,useState } from "react";
import type { CoachMessage } from "@/lib/types";

type CoachMode="decide"|"plan"|"reflect";
type IntelligenceMode="openai"|"anthropic"|"local"|"local-fallback";
type CoachRecommendation={id:string;domain:string;observation:string;reasonItMatters?:string;suggestedAction:string;expectedImpact:string;confidence:string;state:"pending"|"accepted"|"dismissed"|"completed";actionType:string;actionPayload?:Record<string,unknown>};
const MODES:Array<{id:CoachMode;label:string;sub:string}>=[{id:"decide",label:"Decide",sub:"What matters now"},{id:"plan",label:"Plan",sub:"Turn intent into time"},{id:"reflect",label:"Reflect",sub:"Find the pattern"}];
const PROMPTS:Record<CoachMode,string[]>={decide:["What should I focus on today?","What can I safely ignore?","What is my highest-leverage move?"],plan:["Plan the rest of my day.","Turn my top goal into next actions.","What should I schedule first?"],reflect:["How am I progressing?","Where am I losing momentum?","What should I change this week?"]};
const EMPTY_MESSAGES:CoachMessage[]=[];

export function CoachChat({contextSummary,contextReady,initialMessages=EMPTY_MESSAGES,initialPrompts}:{contextSummary:string;contextReady:boolean;initialMessages?:CoachMessage[];initialPrompts?:string[]}){
 const router=useRouter();
 const initial:CoachMessage[]=initialMessages.length?initialMessages:[{id:"welcome",role:"assistant",content:contextReady?`I’m reading your real Project You+ context: ${contextSummary} What decision do you want to make?`:`${contextSummary} Start by asking me what to set up first.`}];
 const[messages,setMessages]=useState<CoachMessage[]>(initial),[recommendations,setRecommendations]=useState<CoachRecommendation[]>([]),[actionError,setActionError]=useState<string|null>(null),[input,setInput]=useState("");
 const[coachMode,setCoachMode]=useState<CoachMode>("decide"),[intelligenceMode,setIntelligenceMode]=useState<IntelligenceMode|null>(null),[suggestions,setSuggestions]=useState(initialPrompts??PROMPTS.decide),[isPending,setIsPending]=useState(false);const listRef=useRef<HTMLDivElement>(null);

 function send(text:string){const trimmed=text.trim();if(!trimmed||isPending)return;const prior=messages.filter(m=>m.id!=="welcome").map(({role,content})=>({role,content}));setMessages(current=>[...current,{id:`u-${Date.now()}`,role:"user",content:trimmed}]);setInput("");setActionError(null);setIsPending(true);void(async()=>{try{const response=await fetch("/api/coach",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:trimmed,history:prior,coachMode})});if(!response.ok)throw new Error("Coach request failed");const data=await response.json() as {reply?:string;mode?:IntelligenceMode;recommendations?:CoachRecommendation[];suggestions?:string[]};setIntelligenceMode(data.mode??null);setRecommendations(data.recommendations??[]);if(data.suggestions?.length)setSuggestions(data.suggestions);setMessages(current=>[...current,{id:`a-${Date.now()}`,role:"assistant",content:data.reply||"I couldn’t generate a response."}]);}catch{setMessages(current=>[...current,{id:`a-${Date.now()}`,role:"assistant",content:"I couldn’t reach the intelligence layer. Try again in a moment."}]);}finally{setIsPending(false);requestAnimationFrame(()=>{const list=listRef.current;if(list)list.scrollTo({top:list.scrollHeight,behavior:"smooth"});});}})();}

 function changeRecommendation(item:CoachRecommendation,operation:"accepted"|"dismissed"|"execute"){if(isPending)return;setActionError(null);setIsPending(true);void(async()=>{try{const response=await fetch(`/api/recommendations/${item.id}`,operation==="execute"?{method:"POST"}:{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({state:operation})});const data=await response.json() as {recommendation?:CoachRecommendation;error?:string};if(!response.ok||!data.recommendation){setActionError(data.error??"The recommendation could not be updated.");return;}setRecommendations(current=>current.map(value=>value.id===item.id?{...value,...data.recommendation}:value));if(operation==="execute"){setMessages(current=>[...current,{id:`a-${Date.now()}`,role:"assistant",content:"Confirmed. Project You+ applied that change and refreshed your context."}]);router.refresh();}}catch{setActionError("The recommendation could not be updated. Try again.");}finally{setIsPending(false);}})();}

 return <div className="flex h-[min(680px,75svh)] min-h-0 flex-col">
  <div className="border-b border-white/[.06] px-4 pb-3 pt-4 sm:px-6"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-[.15em] text-accent-text">Project You+ Intelligence</div><div className="mt-1 text-[11.5px] text-text-3">Grounded in what you have actually added</div></div>{intelligenceMode&&<span className="py-glass-pill">{intelligenceMode==="openai"||intelligenceMode==="anthropic"?"Cloud AI live":intelligenceMode==="local-fallback"?"Local fallback":"Local intelligence"}</span>}</div><div className="mt-4 grid grid-cols-3 gap-2">{MODES.map(mode=>{const active=coachMode===mode.id;return <button key={mode.id} onClick={()=>setCoachMode(mode.id)} className={`py-pressable rounded-[15px] border px-3 py-2.5 text-left ${active?"border-accent/40 bg-accent-soft":"border-white/[.06] bg-white/[.025]"}`}><span className={`block text-[12px] font-semibold ${active?"text-text-1":"text-text-2"}`}>{mode.label}</span><span className="mt-0.5 hidden text-[9px] text-text-3 sm:block">{mode.sub}</span></button>;})}</div></div>
  <div ref={listRef} className="min-h-0 flex-1 overflow-y-auto overscroll-y-contain px-4 pt-5 sm:px-6">
   {messages.map(message=><div key={message.id} className={`mb-3 flex ${message.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-[19px] px-4 py-3 text-[13.5px] leading-relaxed ${message.role==="user"?"border border-white/10 bg-accent text-white shadow-[0_10px_28px_rgba(124,58,237,.22)]":"border border-white/[.06] bg-white/[.035] text-text-1 backdrop-blur-xl"}`}>{message.role === "assistant" ? <CoachMessageContent content={message.content}/> : message.content}</div></div>)}
   {recommendations.filter(item=>item.state==="pending"||item.state==="accepted").map(item=><RecommendationCard key={item.id} item={item} pending={isPending} onChange={changeRecommendation}/>)}
   {actionError&&<div className="mb-3 rounded-[14px] border border-red-400/25 bg-red-400/10 px-3 py-2 text-[11px] text-red-200">{actionError}</div>}
   {isPending&&<div className="mb-3 flex justify-start"><div className="rounded-[18px] border border-white/[.06] bg-white/[.03] px-4 py-3 text-[12px] text-text-3">Reading your context…</div></div>}
  </div>
  {messages.length<=1&&<div className="grid gap-2 px-4 pb-3 sm:grid-cols-3 sm:px-6">{(coachMode==="decide"?suggestions:PROMPTS[coachMode]).map(prompt=><button key={prompt} onClick={()=>send(prompt)} className="py-glass py-pressable rounded-[15px] px-3 py-2.5 text-left text-[11.5px] font-medium leading-snug text-text-1">{prompt}</button>)}</div>}
  <CoachComposer><form onSubmit={event=>{event.preventDefault();send(input);}} className="flex shrink-0 items-center gap-2 border-t border-white/[.06] px-4 py-3.5 sm:px-6"><input value={input} onChange={event=>setInput(event.target.value)} placeholder={coachMode==="decide"?"What decision are you making?":coachMode==="plan"?"What do you need to fit in?":"What do you want to understand?"} aria-label="Message Coach" className="min-h-[46px] min-w-0 flex-1 rounded-full border border-white/[.08] bg-white/[.035] px-4 text-[13px] text-text-1 outline-none backdrop-blur-xl transition focus:border-accent/60"/><button type="submit" className="py-liquid-button h-11 min-h-0 w-11 shrink-0 rounded-full px-0 disabled:opacity-50" aria-label="Send message" disabled={!input.trim()||isPending}>↑</button></form></CoachComposer>
 </div>;
}

function RecommendationCard({item,pending,onChange}:{item:CoachRecommendation;pending:boolean;onChange:(item:CoachRecommendation,operation:"accepted"|"dismissed"|"execute")=>void}){
 const advice=item.actionType==="advice.follow",generatedWorkout=item.actionType==="workout_plan.activate",executable=new Set(["task.complete","task.reschedule","calendar.reschedule","goal.progress","workout.schedule_move"]).has(item.actionType),legacy=!advice&&!generatedWorkout&&!executable;
 const current=typeof item.actionPayload?.previewCurrent==="string"?item.actionPayload.previewCurrent:null,proposed=typeof item.actionPayload?.previewProposed==="string"?item.actionPayload.previewProposed:null;
 return <div className="mb-3 rounded-[18px] border border-accent/25 bg-accent-soft p-4"><div className="flex items-center justify-between gap-3"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-accent-text">Review before applying</span><span className="text-[9px] text-text-3">{item.confidence} confidence</span></div><p className="m-0 mt-2 text-[12.5px] font-semibold leading-relaxed text-text-1">{item.suggestedAction}</p>{current&&proposed&&<div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[12px] border border-white/[.06] bg-black/10 px-3 py-2"><div className="text-[9px] uppercase tracking-[.12em] text-text-3">Current</div><div className="mt-1 text-[11px] text-text-2">{current}</div></div><div className="rounded-[12px] border border-accent/20 bg-accent/10 px-3 py-2"><div className="text-[9px] uppercase tracking-[.12em] text-accent-text">Proposed</div><div className="mt-1 text-[11px] text-text-1">{proposed}</div></div></div>}{item.reasonItMatters&&<p className="m-0 mt-2 text-[10.5px] leading-relaxed text-text-2">{item.reasonItMatters}</p>}{item.expectedImpact&&<p className="m-0 mt-1.5 text-[10.5px] leading-relaxed text-text-3">Expected impact: {item.expectedImpact}</p>}<div className="mt-3 flex gap-2">{generatedWorkout?<Link href="/fitness" className="py-liquid-button min-h-0 px-3 py-2 text-[10px]">Review plan</Link>:legacy?<button disabled={pending||item.state==="accepted"} onClick={()=>onChange(item,"accepted")} className="py-liquid-button min-h-0 px-3 py-2 text-[10px]">{item.state==="accepted"?"Accepted":"Accept"}</button>:advice&&item.state==="pending"?<button disabled={pending} onClick={()=>onChange(item,"accepted")} className="py-liquid-button min-h-0 px-3 py-2 text-[10px]">Accept</button>:<button disabled={pending} onClick={()=>onChange(item,"execute")} className="py-liquid-button min-h-0 px-3 py-2 text-[10px]">{advice?"Mark completed":"Confirm and apply"}</button>}<button disabled={pending} onClick={()=>onChange(item,"dismissed")} className="py-button-secondary min-h-0 px-3 py-2 text-[10px]">Dismiss</button></div></div>;
}
