"use client";

import { useRef,useState,useTransition } from "react";
import type { CoachMessage } from "@/lib/types";
type CoachMode="decide"|"plan"|"reflect";
const MODES:Array<{id:CoachMode;label:string;sub:string}>=[{id:"decide",label:"Decide",sub:"What matters now"},{id:"plan",label:"Plan",sub:"Turn intent into time"},{id:"reflect",label:"Reflect",sub:"Find the pattern"}];
const PROMPTS:Record<CoachMode,string[]>={decide:["What should I focus on today?","What can I safely ignore?","What is my highest-leverage move?"],plan:["Plan the rest of my day.","Turn my top goal into next actions.","What should I schedule first?"],reflect:["How am I progressing?","Where am I losing momentum?","What should I change this week?"]};
export function CoachChat({contextSummary,contextReady}:{contextSummary:string;contextReady:boolean}){const initial:CoachMessage[]=[{id:"welcome",role:"assistant",content:contextReady?`I’m reading your real Project You+ context: ${contextSummary} What decision do you want to make?`:`${contextSummary} Start by asking me what to set up first.`}];const[messages,setMessages]=useState<CoachMessage[]>(initial);const[input,setInput]=useState("");const[coachMode,setCoachMode]=useState<CoachMode>("decide");const[intelligenceMode,setIntelligenceMode]=useState<"claude"|"local"|"local-fallback"|null>(null);const[isPending,startTransition]=useTransition();const listRef=useRef<HTMLDivElement>(null);
function send(text:string){const trimmed=text.trim();if(!trimmed||isPending)return;const prior=messages.filter(m=>m.id!=="welcome").map(({role,content})=>({role,content}));setMessages(c=>[...c,{id:`u-${Date.now()}`,role:"user",content:trimmed}]);setInput("");startTransition(()=>{void(async()=>{try{const response=await fetch("/api/coach",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:trimmed,history:prior,coachMode})});if(!response.ok)throw new Error("Coach request failed");const data=await response.json() as {reply?:string;mode?:"claude"|"local"|"local-fallback"};setIntelligenceMode(data.mode??null);setMessages(c=>[...c,{id:`a-${Date.now()}`,role:"assistant",content:data.reply||"I couldn’t generate a response."}])}catch{setMessages(c=>[...c,{id:`a-${Date.now()}`,role:"assistant",content:"I couldn’t reach the intelligence layer. Try again in a moment."}])}requestAnimationFrame(()=>{const list=listRef.current;if(list)list.scrollTo({top:list.scrollHeight,behavior:"smooth"})})})()})}
return <div className="flex min-h-[590px] flex-col"><div className="border-b border-white/[.06] px-4 pb-3 pt-4 sm:px-6"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-[.15em] text-accent-text">Project You+ Intelligence</div><div className="mt-1 text-[11.5px] text-text-3">Grounded in what you have actually added</div></div>{intelligenceMode&&<span className="py-glass-pill">{intelligenceMode==="claude"?"AI live":intelligenceMode==="local-fallback"?"Local fallback":"Local intelligence"}</span>}</div><div className="mt-4 grid grid-cols-3 gap-2">{MODES.map(mode=>{const active=coachMode===mode.id;return <button key={mode.id} onClick={()=>setCoachMode(mode.id)} className={`py-pressable rounded-[15px] border px-3 py-2.5 text-left ${active?"border-accent/40 bg-accent-soft":"border-white/[.06] bg-white/[.025]"}`}><span className={`block text-[12px] font-semibold ${active?"text-text-1":"text-text-2"}`}>{mode.label}</span><span className="mt-0.5 hidden text-[9px] text-text-3 sm:block">{mode.sub}</span></button>})}</div></div><div ref={listRef} className="flex-1 overflow-y-auto px-4 pt-5 sm:px-6">{messages.map(message=><div key={message.id} className={`mb-3 flex ${message.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-[19px] px-4 py-3 text-[13.5px] leading-relaxed ${message.role==="user"?"border border-white/10 bg-accent text-white shadow-[0_10px_28px_rgba(124,58,237,.22)]":"border border-white/[.06] bg-white/[.035] text-text-1 backdrop-blur-xl"}`}>{message.content}</div></div>)}{isPending&&<div className="mb-3 flex justify-start"><div className="rounded-[18px] border border-white/[.06] bg-white/[.03] px-4 py-3 text-[12px] text-text-3">Reading your context…</div></div>}</div>{messages.length<=1&&<div className="grid gap-2 px-4 pb-3 sm:grid-cols-3 sm:px-6">{PROMPTS[coachMode].map(prompt=><button key={prompt} onClick={()=>send(prompt)} className="py-glass py-pressable rounded-[15px] px-3 py-2.5 text-left text-[11.5px] font-medium leading-snug text-text-1">{prompt}</button>)}</div>}<form onSubmit={e=>{e.preventDefault();send(input)}} className="flex items-center gap-2 border-t border-white/[.06] px-4 py-3.5 sm:px-6"><input value={input} onChange={e=>setInput(e.target.value)} placeholder={coachMode==="decide"?"What decision are you making?":coachMode==="plan"?"What do you need to fit in?":"What do you want to understand?"} className="min-h-[46px] flex-1 rounded-full border border-white/[.08] bg-white/[.035] px-4 text-[13px] text-text-1 outline-none backdrop-blur-xl transition focus:border-accent/60"/><button type="submit" className="py-liquid-button h-11 min-h-0 w-11 shrink-0 rounded-full px-0 disabled:opacity-50" disabled={!input.trim()||isPending}>↑</button></form></div>}
