import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { HealthQuickEntry } from "@/components/health/health-quick-entry";

const LABELS: Record<string,{label:string;unit:string}>={steps:{label:"Steps",unit:""},sleep_minutes:{label:"Sleep",unit:"min"},water_cups:{label:"Water",unit:"cups"},weight_kg:{label:"Weight",unit:"kg"},resting_hr:{label:"Resting HR",unit:"bpm"},recovery_pct:{label:"Recovery",unit:"%"}};
export default async function HealthPage(){
  const supabase=await createClient();
  const {data:metrics}=await supabase.from("health_metrics").select("metric_type,value,recorded_at,source").order("recorded_at",{ascending:false}).limit(80);
  const latest=new Map<string,{value:number;recorded_at:string;source:string}>();
  for(const row of metrics??[]){if(!latest.has(row.metric_type))latest.set(row.metric_type,{value:Number(row.value),recorded_at:row.recorded_at,source:row.source})}
  const hasData=latest.size>0;
  return <main className="py-mobile-shell md:py-shell-narrow"><header className="py-animate-in mb-7 flex items-start justify-between gap-4"><div><div className="py-eyebrow mb-1.5">Body context</div><h1 className="py-title">Health</h1><p className="py-subtitle">Only your real signals appear here. No sample calories, steps, sleep or recovery.</p></div><Link href="/health/scan-meal" className="py-glass flex h-11 w-11 items-center justify-center rounded-full text-[21px] text-text-1">+</Link></header>
  {!hasData&&<section className="py-glass-hero py-animate-in py-stagger-1 p-5"><div className="py-eyebrow text-[#C8AEFF]">Build your baseline</div><h2 className="m-0 mt-3 text-[25px] font-bold tracking-[-.04em] text-white">Health gets useful when it knows your normal.</h2><p className="m-0 mt-2 text-[13px] leading-relaxed text-[#C2BED0]">Start with one or two signals you can maintain. Steps, sleep and water are enough to begin.</p><div className="mt-5 grid grid-cols-3 gap-2">{[["1","Add a signal"],["2","Log meals"],["3","Build history"]].map(([n,t])=><div key={n} className="rounded-[16px] border border-white/10 bg-white/[.035] p-3"><div className="text-[10px] font-bold text-[#C8AEFF]">0{n}</div><div className="mt-1 text-[10.5px] font-medium text-white">{t}</div></div>)}</div></section>}
  {hasData&&<section className="py-animate-in py-stagger-1 grid grid-cols-2 gap-3 sm:grid-cols-3">{[...latest.entries()].slice(0,6).map(([key,item])=>{const meta=LABELS[key]??{label:key.replaceAll("_"," "),unit:""};return <div key={key} className="py-glass-soft p-4"><div className="py-eyebrow">{meta.label}</div><div className="mt-2 text-[25px] font-bold tracking-[-.04em] text-text-1">{formatValue(key,item.value)}{meta.unit&&<span className="ml-1 text-[11px] font-medium text-text-3">{meta.unit}</span>}</div><div className="mt-1 text-[10px] text-text-3">{item.source} · {new Date(item.recorded_at).toLocaleDateString()}</div></div>})}</section>}
  <div className="py-animate-in py-stagger-2 mt-4"><HealthQuickEntry /></div>
  <Link href="/health/scan-meal" className="py-glass-soft py-pressable py-animate-in py-stagger-3 mt-4 flex items-center gap-3 p-4"><span className="py-empty-icon">◎</span><span className="min-w-0 flex-1"><span className="block text-[14px] font-semibold text-text-1">Scan a meal</span><span className="mt-0.5 block text-[11.5px] leading-relaxed text-text-3">Use the meal-photo flow to estimate macros, review them, then confirm.</span></span><span className="text-[20px] text-text-3">›</span></Link>
  <section className="py-glass-soft py-animate-in py-stagger-4 mt-7 p-4"><div className="py-eyebrow text-accent-text">What to add next</div><div className="mt-3 space-y-3 text-[12px] text-text-2"><Tip done={latest.has("steps")} text="Steps — useful for daily movement and recovery context"/><Tip done={latest.has("sleep_minutes")} text="Sleep — helps Project You+ avoid overloading low-energy days"/><Tip done={latest.has("water_cups")} text="Water — simple recovery consistency signal"/></div><Link href="/integrations" className="mt-4 inline-block text-[12px] font-semibold text-accent-text">View future health connections →</Link></section></main>
}
function formatValue(key:string,value:number){if(key==="sleep_minutes")return `${Math.floor(value/60)}h ${Math.round(value%60)}`;return Number.isInteger(value)?String(value):value.toFixed(1)}
function Tip({done,text}:{done:boolean;text:string}){return <div className="flex items-start gap-2.5"><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border text-[9px] ${done?"border-positive bg-positive-soft text-positive":"border-border text-transparent"}`}>✓</span><span>{text}</span></div>}
