import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { NavIcon } from "@/components/layout/nav-icon";
import { logSupplementToday } from "@/lib/actions/supplements";

const LABELS:Record<string,{label:string;unit:string;why:string}>={steps:{label:"Steps",unit:"",why:"Daily movement"},sleep_minutes:{label:"Sleep",unit:"min",why:"Recovery context"},water_cups:{label:"Water",unit:"cups",why:"Hydration context"},weight_kg:{label:"Weight",unit:"kg",why:"Long-term trend"},resting_hr:{label:"Resting HR",unit:"bpm",why:"Recovery trend"},recovery_pct:{label:"Recovery",unit:"%",why:"Readiness context"}};
const DAY_NAMES=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
type Session={key:string;day:string;dayIndex:number;title:string;focus?:string;duration:number};

export default async function HealthPage(){
 const supabase=await createClient();const now=new Date();const today=localDate(now);const start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const week=new Date(start);week.setDate(week.getDate()-6);
 const [{data:metrics},{data:nutrition},{data:weekNutrition},{data:plan},{data:planLogs},{data:supplements},{data:supplementLogs}]=await Promise.all([
  supabase.from("health_metrics").select("metric_type,value,recorded_at,source").order("recorded_at",{ascending:false}).limit(80),
  supabase.from("nutrition_logs").select("id,meal_name,calories,protein_g,carbs_g,fat_g,logged_at,source").gte("logged_at",start.toISOString()).lt("logged_at",end.toISOString()).order("logged_at"),
  supabase.from("nutrition_logs").select("logged_at").gte("logged_at",week.toISOString()).lt("logged_at",end.toISOString()),
  supabase.from("workout_plans").select("id,title,goal,days_per_week,session_minutes,schedule").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  supabase.from("workout_plan_logs").select("plan_id,session_key,completed_on").gte("completed_on",localDate(week)).lte("completed_on",today),
  supabase.from("supplements").select("id,name,dosage,timing,frequency,active").eq("active",true).order("created_at"),
  supabase.from("supplement_logs").select("supplement_id,logged_on").gte("logged_on",localDate(week)).lte("logged_on",today)
 ]);
 const latest=new Map<string,{value:number;recorded_at:string;source:string}>();for(const row of metrics??[]){if(!latest.has(row.metric_type))latest.set(row.metric_type,{value:Number(row.value),recorded_at:row.recorded_at,source:row.source})}
 const meals=nutrition??[];const nutritionTotal=meals.reduce((s,r)=>({calories:s.calories+Number(r.calories||0),protein:s.protein+Number(r.protein_g||0),carbs:s.carbs+Number(r.carbs_g||0),fat:s.fat+Number(r.fat_g||0)}),{calories:0,protein:0,carbs:0,fat:0});
 const schedule=(Array.isArray(plan?.schedule)?plan.schedule:[]) as Session[];const todaySession=schedule.find(s=>s.dayIndex===now.getDay())??null;const completedPlan=new Set((planLogs??[]).filter(x=>x.plan_id===plan?.id).map(x=>`${x.completed_on}:${x.session_key}`));
 const due=(supplements??[]).filter(s=>isDue(s.frequency,now.getDay(),Boolean(todaySession)));const todaySuppDone=new Set((supplementLogs??[]).filter(x=>x.logged_on===today).map(x=>x.supplement_id));
 const trainingPct=trainingAdherence(schedule,completedPlan,now);const dietPct=dietConsistency(weekNutrition??[],now);const supplementPct=due.length?Math.round(due.filter(x=>todaySuppDone.has(x.id)).length/due.length*100):100;const consistencyPct=Math.round((trainingPct+dietPct+supplementPct)/3);const healthScore=Math.round(trainingPct*.35+dietPct*.30+supplementPct*.20+consistencyPct*.15);

 return <main className="py-mobile-shell md:py-shell-narrow">
  <header className="mb-5"><div className="py-glass-hero overflow-hidden p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="text-[11px] font-semibold text-text-3">Health operating system</div><h1 className="m-0 mt-1.5 text-[31px] font-bold tracking-[-.05em] text-text-1">Your health, in rhythm.</h1><p className="m-0 mt-2 max-w-[470px] text-[12px] leading-relaxed text-text-2">Training, diet tracking, supplements, and consistency working together instead of living in separate apps.</p></div><HealthRing value={healthScore}/></div><div className="mt-5 grid grid-cols-4 gap-2"><Mini label="Training" value={trainingPct}/><Mini label="Diet" value={dietPct}/><Mini label="Protocol" value={supplementPct}/><Mini label="Consistency" value={consistencyPct}/></div></div></header>

  <section className="mt-4"><div className="mb-3 flex items-end justify-between"><div><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">Training plan</h2><p className="m-0 mt-1 text-[10.5px] text-text-3">Your actual programmed workout week.</p></div><Link href="/fitness" className="text-[11px] font-semibold text-accent-text">Edit plan</Link></div><Link href="/fitness" className="py-glass-soft py-pressable block p-4"><div className="flex items-start gap-3"><span className="py-icon-tile text-accent-text"><NavIcon name="fitness" className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="text-[14px] font-semibold text-text-1">{plan?.title??"Build your workout plan"}</div><div className="mt-1 text-[10.5px] text-text-3">{todaySession?`${todaySession.title} · ${todaySession.duration} min today`:plan?"Recovery day today":"Choose exact training days and let Project You+ build the week."}</div></div></div>{schedule.length>0&&<div className="mt-4 grid grid-cols-7 gap-1.5">{[1,2,3,4,5,6,0].map(day=>{const session=schedule.find(s=>s.dayIndex===day);return <div key={day} className={`rounded-[13px] border px-1 py-2.5 text-center ${session?"border-accent bg-accent-soft":"border-border bg-surface/40"}`}><div className={`text-[8.5px] font-semibold ${session?"text-accent-text":"text-text-3"}`}>{DAY_NAMES[day].slice(0,3)}</div><div className="mt-1 text-[7.5px] text-text-3">{session?"train":"off"}</div></div>})}</div>}</Link></section>

  <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">Diet tracker</h2><p className="m-0 mt-1 text-[10.5px] text-text-3">Nutrition AI lives here, organized around what you actually log.</p></div><Link href="/health/scan-meal" className="py-glass-pill">Nutrition AI</Link></div><div className="py-glass-soft overflow-hidden"><Link href="/health/scan-meal" className="flex items-center gap-3 border-b border-border p-4"><span className="flex h-11 w-11 items-center justify-center rounded-[15px] bg-accent-soft text-[18px] font-semibold text-accent-text">◎</span><div className="min-w-0 flex-1"><div className="text-[14px] font-semibold text-text-1">Scan or log a meal</div><div className="mt-0.5 text-[10.5px] text-text-3">Photograph food, review the estimate, then save it.</div></div><span className="text-text-3">›</span></Link><div className="grid grid-cols-4 gap-px bg-border"><Metric label="Calories" value={`${Math.round(nutritionTotal.calories)}`}/><Metric label="Protein" value={`${round(nutritionTotal.protein)}g`}/><Metric label="Carbs" value={`${round(nutritionTotal.carbs)}g`}/><Metric label="Fat" value={`${round(nutritionTotal.fat)}g`}/></div>{meals.length>0&&<div className="px-4">{meals.map(meal=><div key={meal.id} className="flex items-center gap-3 border-t border-border py-3 first:border-t-0"><div className="min-w-0 flex-1"><div className="truncate text-[12.5px] font-semibold text-text-1">{meal.meal_name||"Meal"}</div><div className="mt-0.5 text-[9.5px] text-text-3">{meal.source==="nutrition_ai"?"Nutrition AI":"Manual"} · P {round(Number(meal.protein_g))}g</div></div><div className="text-[11px] font-semibold text-text-2">{meal.calories} kcal</div></div>)}</div>}</div></section>

  <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">Supplements</h2><p className="m-0 mt-1 text-[10.5px] text-text-3">Today’s scheduled protocol, as a checklist.</p></div><div className="flex gap-2"><Link href="/reminders" className="text-[10.5px] font-semibold text-text-3">Reminder</Link><Link href="/supplements" className="text-[10.5px] font-semibold text-accent-text">Manage</Link></div></div><div className="py-glass-soft divide-y divide-border px-4">{due.length?due.map(item=>{const checked=todaySuppDone.has(item.id);return <div key={item.id} className="flex items-center gap-3 py-3.5"><form action={logSupplementToday.bind(null,item.id)}><button disabled={checked} className={`py-check ${checked?"py-check-done":""}`}>{checked?"✓":""}</button></form><div className="min-w-0 flex-1"><div className={`text-[13px] font-semibold ${checked?"text-text-3 line-through":"text-text-1"}`}>{item.name}</div><div className="mt-0.5 text-[9.5px] capitalize text-text-3">{item.dosage||"Dose not set"} · {item.timing.replaceAll("_"," ")}</div></div></div>}):<div className="py-4 text-[11px] text-text-3">Nothing scheduled today.</div>}</div></section>

  <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><h2 className="m-0 text-[20px] font-semibold tracking-[-.03em] text-text-1">Vitals & recovery</h2><p className="m-0 mt-1 max-w-[520px] text-[10.5px] leading-relaxed text-text-3">These are optional context signals. They help Project You+ understand recovery and trends; they are not diagnoses and they do not need to be filled in manually if you connect a health source later.</p></div><Link href="/integrations" className="text-[10.5px] font-semibold text-accent-text">Connections</Link></div>{latest.size?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[...latest.entries()].slice(0,6).map(([key,item])=>{const meta=LABELS[key]??{label:key.replaceAll("_"," "),unit:"",why:"Health context"};return <div key={key} className="py-glass-soft p-4"><div className="text-[9.5px] text-text-3">{meta.label}</div><div className="mt-2 text-[22px] font-semibold tracking-[-.035em] text-text-1">{formatValue(key,item.value)}{meta.unit&&<span className="ml-1 text-[9px] font-medium text-text-3">{meta.unit}</span>}</div><div className="mt-1 text-[8.5px] text-text-3">{meta.why}</div></div>})}</div>:<div className="py-glass-soft p-4 text-[11.5px] leading-relaxed text-text-3">No vitals connected yet. That’s fine—Training, Diet Tracker, and Supplements work without them.</div>}</section>
 </main>
}
function HealthRing({value}:{value:number}){return <div className="relative flex h-20 w-20 shrink-0 items-center justify-center rounded-full" style={{background:`conic-gradient(var(--accent) ${value*3.6}deg,var(--surface-3) 0deg)`}}><div className="flex h-[64px] w-[64px] flex-col items-center justify-center rounded-full bg-surface"><div className="text-[22px] font-bold tracking-[-.04em] text-text-1">{value}</div><div className="text-[7.5px] font-semibold uppercase tracking-[.08em] text-text-3">health</div></div></div>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-[14px] border border-border bg-surface/40 p-2.5 text-center"><div className="text-[13px] font-bold text-text-1">{value}%</div><div className="mt-0.5 text-[7.5px] text-text-3">{label}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-surface px-2 py-3 text-center"><div className="text-[12px] font-semibold text-text-1">{value}</div><div className="mt-0.5 text-[7.5px] text-text-3">{label}</div></div>}
function trainingAdherence(schedule:Session[],logs:Set<string>,now:Date){if(!schedule.length)return 0;const monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(12,0,0,0);let expected=0,done=0;for(const s of schedule){const d=new Date(monday);const offset=(s.dayIndex+6)%7;d.setDate(monday.getDate()+offset);if(d<=now){expected++;if(logs.has(`${localDate(d)}:${s.key}`))done++}}return expected?Math.round(done/expected*100):100}
function dietConsistency(rows:Array<{logged_at:string}>,now:Date){const days=new Set(rows.map(r=>localDate(new Date(r.logged_at))));let expected=0,done=0;for(let i=6;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);expected++;if(days.has(localDate(d)))done++}return Math.round(done/expected*100)}
function isDue(frequency:string,day:number,training:boolean){if(frequency==="daily")return true;if(frequency==="weekdays")return day>=1&&day<=5;if(frequency==="training_days")return training;if(frequency.startsWith("weekly_"))return frequency===`weekly_${DAY_NAMES[day].toLowerCase()}`;if(frequency==="weekly")return day===1;return false}
function formatValue(key:string,value:number){if(key==="sleep_minutes")return `${Math.floor(value/60)}h ${Math.round(value%60)}`;return Number.isInteger(value)?String(value):value.toFixed(1)}
function round(value:number){return Math.round(value*10)/10}
function localDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
