create table if not exists public.ai_agents (
  agent_key text primary key,
  name text not null,
  description text,
  category text not null check (category in ('orchestrator','builder','qa','backend','design','product')),
  status text not null default 'idle' check (status in ('idle','queued','running','blocked','error','offline')),
  enabled boolean not null default true,
  capabilities jsonb not null default '[]'::jsonb,
  last_run_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_agent_runs (
  id bigint generated by default as identity primary key,
  agent_key text not null references public.ai_agents(agent_key) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  run_type text not null,
  title text not null,
  status text not null default 'queued' check (status in ('queued','running','passed','failed','cancelled','blocked')),
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_agent_findings (
  id bigint generated by default as identity primary key,
  run_id bigint references public.ai_agent_runs(id) on delete cascade,
  agent_key text not null references public.ai_agents(agent_key) on delete cascade,
  severity text not null default 'info' check (severity in ('info','low','medium','high','critical')),
  title text not null,
  detail text,
  path text,
  status text not null default 'open' check (status in ('open','acknowledged','resolved','dismissed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.ai_agents enable row level security;
alter table public.ai_agent_runs enable row level security;
alter table public.ai_agent_findings enable row level security;

drop policy if exists "admins read ai agents" on public.ai_agents;
create policy "admins read ai agents" on public.ai_agents for select to authenticated using (private.is_app_admin());
drop policy if exists "admins manage ai agents" on public.ai_agents;
create policy "admins manage ai agents" on public.ai_agents for all to authenticated using (private.is_app_admin()) with check (private.is_app_admin());

drop policy if exists "admins read ai agent runs" on public.ai_agent_runs;
create policy "admins read ai agent runs" on public.ai_agent_runs for select to authenticated using (private.is_app_admin());
drop policy if exists "admins manage ai agent runs" on public.ai_agent_runs;
create policy "admins manage ai agent runs" on public.ai_agent_runs for all to authenticated using (private.is_app_admin()) with check (private.is_app_admin());

drop policy if exists "admins read ai agent findings" on public.ai_agent_findings;
create policy "admins read ai agent findings" on public.ai_agent_findings for select to authenticated using (private.is_app_admin());
drop policy if exists "admins manage ai agent findings" on public.ai_agent_findings;
create policy "admins manage ai agent findings" on public.ai_agent_findings for all to authenticated using (private.is_app_admin()) with check (private.is_app_admin());

create index if not exists ai_agent_runs_agent_created_idx on public.ai_agent_runs(agent_key, created_at desc);
create index if not exists ai_agent_runs_status_created_idx on public.ai_agent_runs(status, created_at desc);
create index if not exists ai_agent_findings_status_created_idx on public.ai_agent_findings(status, created_at desc);
create index if not exists ai_agent_findings_agent_created_idx on public.ai_agent_findings(agent_key, created_at desc);

insert into public.ai_agents (agent_key,name,description,category,status,enabled,capabilities)
values
('orchestrator','Orchestrator','Coordinates the Project You+ AI development team and routes work safely.','orchestrator','idle',true,'["plan work","route jobs","summarize results","enforce approvals"]'::jsonb),
('builder','Builder','Implements app changes in feature branches and prepares pull requests.','builder','idle',true,'["code changes","branch work","build fixes","pull requests"]'::jsonb),
('qa','QA','Runs automated product checks, browser journeys and regression testing.','qa','idle',true,'["auth flows","navigation","mobile regression","route checks","console errors"]'::jsonb),
('backend','Backend','Reviews Supabase schema, RLS, migrations, auth and database health.','backend','idle',true,'["RLS review","migration review","database health","auth checks"]'::jsonb),
('design','Design','Checks implementation consistency against Project You+ visual standards and approved design source.','design','idle',true,'["visual QA","brand consistency","responsive review","design findings"]'::jsonb),
('product','Product Analyst','Turns usage and funnel signals into prioritized product recommendations.','product','idle',true,'["funnel analysis","retention signals","feature usage","recommendations"]'::jsonb)
on conflict (agent_key) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  capabilities = excluded.capabilities,
  updated_at = now();
