"use client";

import { useState, useTransition } from "react";
import { saveFinancialGoal } from "@/lib/actions/finance";
import type { FinanceAccount, GoalProjection } from "@/lib/finance/types";

export function FinancialGoals({ goals, accounts }: { goals: GoalProjection[]; accounts: FinanceAccount[] }) {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<GoalProjection | null>(null);
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string | null>(null);
  function close() { setOpen(false); setEditing(null); setMessage(null); }
  function add() { setEditing(null); setOpen(true); setMessage(null); }
  function edit(goal: GoalProjection) { setEditing(goal); setOpen(true); setMessage(null); }
  function submit(formData: FormData) { setMessage(null); startTransition(() => { void saveFinancialGoal(formData).then((result) => { setMessage(result.error); if (!result.error) close(); }); }); }
  return <section className="mt-7">
    <div className="mb-3 flex items-end justify-between"><div><div className="text-[11px] text-text-3">Projections</div><h2 className="m-0 mt-1 text-[21px] font-semibold tracking-[-.03em] text-text-1">Financial goals</h2></div><button type="button" onClick={open ? close : add} className="text-[11px] font-semibold text-accent-text">{open ? "Close" : "+ Add goal"}</button></div>
    {open && <form key={editing?.goalId ?? "new"} action={submit} className="py-glass-soft mb-3 grid gap-2.5 p-4 sm:grid-cols-2">
      {editing && <input type="hidden" name="id" value={editing.goalId}/>}<input name="title" defaultValue={editing?.name ?? ""} required maxLength={120} placeholder="Emergency fund" className="py-input min-h-[44px] py-2 text-[13px]"/><select name="type" defaultValue={editing?.financialGoalType ?? "emergency_fund"} className="py-input min-h-[44px] text-[13px]"><option value="emergency_fund">Emergency fund</option><option value="savings">Savings</option><option value="debt_payoff">Debt payoff</option><option value="purchase">Purchase</option><option value="investment">Investment</option><option value="custom">Other</option></select><input name="currentAmount" defaultValue={editing?.currentAmount ?? ""} required min="0" max="1000000000" step="0.01" type="number" placeholder="Current amount" className="py-input min-h-[44px] py-2 text-[13px]"/><input name="targetAmount" defaultValue={editing?.targetAmount || ""} required min="0.01" max="1000000000" step="0.01" type="number" placeholder="Target amount" className="py-input min-h-[44px] py-2 text-[13px]"/><input name="monthlyContribution" defaultValue={editing?.targetMonthlyContribution ?? ""} min="0" max="1000000000" step="0.01" type="number" placeholder="Monthly contribution (optional)" className="py-input min-h-[44px] py-2 text-[13px]"/><input name="deadline" defaultValue={editing?.targetPaceDate ?? ""} type="date" className="py-input min-h-[44px] py-2 text-[13px]"/>{accounts.length > 0 && <select name="linkedAccountId" defaultValue={editing?.linkedAccountId ?? ""} className="py-input min-h-[44px] text-[13px] sm:col-span-2"><option value="">Track manually</option>{accounts.map((account) => <option key={account.id} value={account.id}>Link {account.name}</option>)}</select>}<button disabled={pending} className="py-button-primary min-h-[44px] sm:col-span-2 disabled:opacity-50">{pending ? "Saving…" : editing ? "Confirm changes" : "Confirm goal"}</button>{message && <p className="m-0 text-[11px] text-danger sm:col-span-2">{message}</p>}
    </form>}
    {goals.length ? <div className="space-y-2.5">{goals.map((goal) => <article key={goal.goalId} className="py-glass-soft p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="m-0 truncate text-[13px] font-semibold text-text-1">{goal.name}</h3><p className="m-0 mt-1 text-[9.5px] text-text-3">{goal.targetAmount > 0 ? `${money(goal.currentAmount)} of ${money(goal.targetAmount)}` : "Set a numeric target to activate projections"}</p></div><div className="flex items-center gap-2"><span className={statusClass(goal.status)}>{goal.targetAmount > 0 ? statusLabel(goal.status) : "Needs setup"}</span><button type="button" onClick={() => edit(goal)} className="text-[9.5px] font-semibold text-accent-text">Edit</button></div></div>{goal.targetAmount > 0 && <><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><span className="block h-full rounded-full bg-accent" style={{ width: `${goal.progressPct}%` }}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-[9.5px] text-text-3"><span>{Math.round(goal.progressPct)}% complete</span><span className="text-right">{projection(goal)}</span></div></>}</article>)}</div> : <div className="py-glass-soft p-4 text-[12px] leading-relaxed text-text-3">No financial goal is configured. Add a target to see current pace, required pace, and a grounded projection.</div>}
  </section>;
}

function projection(goal: GoalProjection) { if (goal.status === "completed") return "Target reached"; if (!goal.requiredMonthlyPace) return "Add a date or monthly target"; return `${money(goal.requiredMonthlyPace)}/mo required`; }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
function statusLabel(status: GoalProjection["status"]) { return status === "on_track" ? "On track" : status === "insufficient_data" ? "Calibrating" : status.charAt(0).toUpperCase() + status.slice(1); }
function statusClass(status: GoalProjection["status"]) { return `py-glass-pill text-[9px] ${status === "completed" || status === "ahead" || status === "on_track" ? "text-positive" : status === "behind" ? "text-warn" : "text-text-3"}`; }
