"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { disconnectPlaid, refreshPlaid } from "@/lib/actions/integrations";
import type { FinanceOverview } from "@/lib/finance/types";

export function PlaidConnectionStatus({ connection }: { connection: FinanceOverview["connection"] }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null); const [confirmDisconnect, setConfirmDisconnect] = useState(false);
  function refresh() { setMessage(null); startTransition(() => { void refreshPlaid().then((result) => setMessage(result.error ?? "Accounts refreshed.")); }); }
  function disconnect() { setMessage(null); startTransition(() => { void disconnectPlaid().then((result) => { setMessage(result.error ?? "Plaid disconnected."); if (!result.error) setConfirmDisconnect(false); }); }); }
  return <section className="mt-7 py-glass-soft p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[9.5px] font-semibold uppercase tracking-[.12em] text-text-3">Plaid connection</div><div className="mt-1 text-[13px] font-semibold capitalize text-text-1">{connection.status.replace("_", " ")}</div></div><span className={`h-2.5 w-2.5 rounded-full ${connection.status === "connected" ? "bg-positive" : connection.status === "needs_attention" ? "bg-warn" : "bg-white/20"}`}/></div><p className="m-0 mt-2 text-[10px] leading-relaxed text-text-3">{connection.lastSyncedAt ? `Last refreshed ${new Date(connection.lastSyncedAt).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}.` : "No Plaid sync has completed yet."}{connection.environment ? ` ${connection.environment} environment.` : ""}</p><div className="mt-3 flex gap-2">{connection.status === "connected" && <button type="button" disabled={pending} onClick={refresh} className="py-button-secondary min-h-[40px] flex-1 disabled:opacity-50">{pending ? "Refreshing…" : "Refresh accounts"}</button>}<Link href="/money/connect" className="py-button-secondary flex min-h-[40px] flex-1 items-center justify-center">{connection.status === "connected" ? "Manage" : "Connect"}</Link></div>{connection.status === "connected" && <div className="mt-2">{confirmDisconnect ? <div className="rounded-2xl border border-danger/20 bg-danger/5 p-3"><p className="m-0 text-[10.5px] leading-relaxed text-text-2">Disconnecting removes Plaid-imported accounts and transactions from Project You+. Manual records stay.</p><div className="mt-2 flex gap-2"><button type="button" disabled={pending} onClick={disconnect} className="min-h-[38px] flex-1 rounded-xl bg-danger/15 text-[10px] font-semibold text-danger">{pending ? "Disconnecting…" : "Confirm disconnect"}</button><button type="button" onClick={() => setConfirmDisconnect(false)} className="min-h-[38px] flex-1 text-[10px] font-semibold text-text-3">Cancel</button></div></div> : <button type="button" onClick={() => setConfirmDisconnect(true)} className="w-full py-2 text-[10px] font-medium text-text-3">Disconnect Plaid</button>}</div>}{message && <p className={`m-0 mt-2 text-[10.5px] ${message === "Accounts refreshed." || message === "Plaid disconnected." ? "text-positive" : "text-danger"}`}>{message}</p>}</section>;
}
